edition = "2024"
style_edition = "2024"

# stable
reorder_imports = true

# unstable (nightly)
comment_width = 80
format_strings = true
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
normalize_comments = true
overflow_delimited_expr = true
wrap_comments = false # See: <https://github.com/rust-lang/rustfmt/pull/5943>
