[package]
description = "The in-repo ticket format: parsing, rendering, and file operations."
name = "ticket"

authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
camino = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }
serde_json = { workspace = true, features = ["std"] }

[dev-dependencies]
camino-tempfile = { workspace = true }
indoc = { workspace = true }

[lints]
workspace = true
