import AppKit
import Foundation

/// A workspace on disk for one UI test, and the scratch directories the app
/// under test writes into.
///
/// The layout is JP's storage format: `.jp/.id` names the workspace, and each
/// conversation is a directory holding `metadata.json`, `base_config.json` and
/// `events.json`. A UI test runs outside the app's process and cannot reach the
/// Rust library that would otherwise write them, so they are written here by
/// hand. `crates/jp_ffi/src/lib_tests.rs` pins the same shape from the Rust
/// side; a change to one needs the other.
///
/// Paired with ``remove()`` through `defer` rather than released by a `deinit`:
/// ARC may drop an object right after its last mention, which can be while the
/// app is still reading the directory.
struct WorkspaceFixture {
    /// Everything the fixture owns.
    let root: URL

    /// The workspace directory the app is told to open.
    let workspacePath: String

    /// The pasteboard the app under test copies to.
    ///
    /// A real pasteboard that nobody is looking at, so Copy Link can be checked
    /// without destroying whatever the person at the keyboard last copied.
    /// Named per fixture, so a stale value from an earlier run cannot be read
    /// back as this one's.
    let pasteboardName: String

    /// The workspace's directory name, which the window shows as its title.
    var name: String {
        URL(fileURLWithPath: workspacePath).lastPathComponent
    }

    /// Create a fixture holding `conversations`.
    ///
    /// The workspace ID is written rather than left for JP to mint, because JP
    /// derives one from the current millisecond. A fixed one keeps the
    /// user-local store path stable across runs.
    static func make(
        named name: String = "my-workspace",
        conversations: [FixtureConversation] = []
    ) throws -> WorkspaceFixture {
        let root = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("jp-uitests-\(UUID().uuidString)")
        let workspace = root.appendingPathComponent(name)
        let store = workspace.appendingPathComponent(".jp")

        let files = FileManager.default
        try files.createDirectory(at: store, withIntermediateDirectories: true)

        // `Id::load` reads the last line, and rejects anything that is not five
        // characters of `[0-9a-z]`.
        let preamble = "DO NOT EDIT THIS FILE! IT IS AUTO-GENERATED BY JP."
        try "\(preamble)\nuitst\n"
            .write(to: store.appendingPathComponent(".id"), atomically: true, encoding: .utf8)

        for conversation in conversations {
            try conversation.write(into: store)
        }

        // The app resolves `HOME` for anything it keeps in the home directory,
        // so the directory has to exist before it looks.
        for scratch in ["user-data", "state", "home"] {
            try files.createDirectory(
                at: root.appendingPathComponent(scratch),
                withIntermediateDirectories: true
            )
        }

        return WorkspaceFixture(
            root: root,
            workspacePath: workspace.path,
            pasteboardName: "computer.jp.jean-pierre.uitest.\(UUID().uuidString)"
        )
    }

    /// What to launch the app with, so nothing it writes reaches the state the
    /// developer shares with it.
    ///
    /// - `JP_WORKSPACE` names the workspace to open. The app prefers it over
    ///   both its stored path and its most recent workspace.
    /// - `JP_USER_DATA_DIR` moves the user-local conversation store, which
    ///   opening a workspace creates.
    /// - `JP_DEBUG_STATE_DIR` moves the recent-workspace list into a file here,
    ///   instead of the list the app shares with the system. That list needs
    ///   Full Disk Access to read back, so a test could neither inspect nor
    ///   restore it.
    /// - `HOME` moves whatever else the app resolves from the home directory.
    /// - `JP_DEBUG_PASTEBOARD` moves Copy Link off the system pasteboard. Read
    ///   only by a debug build; see `DebugState.pasteboard`.
    /// - `JP_DEBUG_DISABLE_ANIMATIONS` stops the app animating. XCUITest waits
    ///   for the app to stop moving before every action it synthesizes, so an
    ///   animation is time added to every test that triggers one.
    ///
    /// Window state saved by `@SceneStorage` reaches none of these, because it
    /// is keyed by bundle identifier. ``AppUnderTest`` handles that with a
    /// launch argument.
    var environment: [String: String] {
        [
            "JP_WORKSPACE": workspacePath,
            "JP_USER_DATA_DIR": root.appendingPathComponent("user-data").path,
            "JP_DEBUG_STATE_DIR": root.appendingPathComponent("state").path,
            "HOME": root.appendingPathComponent("home").path,
            "JP_DEBUG_PASTEBOARD": pasteboardName,
            "JP_DEBUG_DISABLE_ANIMATIONS": "1",
        ]
    }

    /// The process id of the app launched against this fixture.
    ///
    /// Written by the app itself, into the state directory it was pointed at.
    /// Exact rather than matched on a name or a bundle identifier, which is
    /// what makes it safe to act on: the developer's own copy of JP shares both
    /// of those and must never be touched.
    var appProcessID: String? {
        let file = root.appendingPathComponent("state/pid")
        guard let text = try? String(contentsOf: file, encoding: .utf8) else { return nil }

        return text.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// The fields of the last interval the app traced under `name`.
    ///
    /// The app writes one JSON object per line into the state directory it was
    /// pointed at, which is how a test reaches a fact about the app that leaves no
    /// mark on screen. Live re-wrapping is one: whether text re-wrapped *during* a
    /// window drag or only once it ended is invisible afterwards, because both end
    /// with the text correct.
    ///
    /// Numbers come back as `Double` whatever the app wrote, since JSON does not
    /// distinguish them and a caller comparing counts does not care.
    ///
    /// `nil` when the app has traced nothing under that name.
    func lastTracedInterval(named name: String) -> [String: Double]? {
        let file = root.appendingPathComponent("state/trace.jsonl")
        guard let text = try? String(contentsOf: file, encoding: .utf8) else { return nil }

        for line in text.split(separator: "\n").reversed() {
            guard
                let data = line.data(using: .utf8),
                let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
                let fields = object["fields"] as? [String: Any],
                fields["message"] as? String == name
            else { continue }

            return fields.compactMapValues { $0 as? Double ?? ($0 as? Int).map(Double.init) }
        }

        return nil
    }

    /// The text the app last copied, or `nil` if it has copied nothing.
    ///
    /// Reads the fixture's own pasteboard, never the system one. That is what
    /// makes checking Copy Link safe, and it is enforced rather than trusted:
    /// `ClipboardPolicyTests` fails on any mention of the system pasteboard in
    /// this directory.
    func copiedText() -> String? {
        NSPasteboard(name: NSPasteboard.Name(pasteboardName)).string(forType: .string)
    }

    func remove() {
        // A named pasteboard outlives the process that made one, so this run's
        // is handed back rather than left for the pasteboard server to keep.
        NSPasteboard(name: NSPasteboard.Name(pasteboardName)).releaseGlobally()

        try? FileManager.default.removeItem(at: root)
    }
}

/// One conversation to write into a fixture.
///
/// Every value is fixed by the test that builds it, including the ID: JP mints
/// one from the wall clock, and a test that did the same could not name the row
/// it wanted afterwards.
struct FixtureConversation {
    /// The decisecond timestamp identifying the conversation.
    ///
    /// Also its directory name. JP writes `<id>-<slugged title>`, but the loader
    /// finds a conversation by the ID prefix, so the bare ID is enough and saves
    /// reproducing the slug rule here.
    let id: String

    /// The title, shown as the row's first line.
    let title: String

    /// When the conversation was last activated, in JP's stored spelling.
    ///
    /// This is what the list sorts on, most recent first.
    let lastActivatedAt: String

    /// When the conversation was pinned, in JP's stored spelling, or `nil` for a
    /// conversation that is not pinned.
    ///
    /// Left out of `metadata.json` entirely when `nil`, which is how JP stores an
    /// unpinned conversation and what the app's decoder reads as "not pinned".
    var pinnedAt: String?

    /// The stored event stream, oldest first.
    let events: [[String: String]]

    /// A message from the user, as storage holds one.
    static func userMessage(
        at timestamp: String, from author: String, _ text: String
    ) -> [String: String] {
        ["timestamp": timestamp, "type": "chat_request", "author": author, "content": text]
    }

    /// A message from the assistant, as storage holds one.
    static func assistantMessage(at timestamp: String, _ text: String) -> [String: String] {
        ["timestamp": timestamp, "type": "chat_response", "message": text]
    }

    /// The `jp://` URI the app copies and drags for this conversation.
    var uri: String {
        "jp://\(id)"
    }

    /// What the row's second line reads, pluralized the way the app does.
    var eventCountLabel: String {
        events.count == 1 ? "1 event" : "\(events.count) events"
    }

    /// Write the conversation into a workspace's `.jp` store.
    fileprivate func write(into store: URL) throws {
        let directory =
            store
            .appendingPathComponent("conversations")
            .appendingPathComponent(id)
        try FileManager.default.createDirectory(
            at: directory, withIntermediateDirectories: true)

        var metadata = ["title": title, "last_activated_at": lastActivatedAt]
        if let pinnedAt {
            metadata["pinned_at"] = pinnedAt
        }

        try Self.writeJSON(metadata, to: directory.appendingPathComponent("metadata.json"))

        try Self.baseConfig.write(
            to: directory.appendingPathComponent("base_config.json"),
            atomically: true,
            encoding: .utf8
        )

        try Self.writeJSON(events, to: directory.appendingPathComponent("events.json"))
    }

    /// The smallest `base_config.json` a conversation can be stored with.
    ///
    /// Its presence tells the loader the conversation is in the current storage
    /// format, and its contents have to finalize into a whole config: a
    /// conversation whose base config is empty fails to load, and the app shows
    /// "Could Not Read Conversation" where the transcript belongs. These two
    /// settings are the ones with no default to fall back on.
    ///
    /// The same string is pinned in `crates/jp_ffi/src/lib_tests.rs`, which
    /// reads this exact layout back through the library the app calls. That
    /// test is what names a newly required setting, in seconds; here the same
    /// breakage looks like a UI test waiting on a pane that never fills.
    private static let baseConfig = """
        {"assistant":{"model":{"id":{"provider":"anthropic","name":"test"}}},\
        "conversation":{"tools":{"*":{"run":"ask"}}}}
        """

    private static func writeJSON(_ value: Any, to url: URL) throws {
        let data = try JSONSerialization.data(withJSONObject: value)
        try data.write(to: url)
    }
}
