[conversation.tools.git_list_patches]
enable = "explicit"
run = "unattended"
style.inline_results = "full"

source = "local"
command = "just serve-tools {{context}} {{tool}}"
summary = "List all patches for a given file that can be staged with `git_stage_patch`."
description = """
The listed patches have a unique identifier, which can be used in \
`git_stage_patch` to stage the patch in the repository cache.
"""

examples = """
```json
{"files": ["crates/jp_config/src/conversation/tool.rs", "crates/jp_llm/src/builtin.rs"]}
```
"""

[conversation.tools.git_list_patches.parameters.files]
type = "array"
required = true
items.type = "string"
summary = "One or more files to list Git patches for."
