[conversation.tools.web_fetch]
enable = false
source = "local"
command = "just serve-tools {{context}} {{tool}}"
summary = "Fetch the contents of a web page over HTTP(S)."

examples = """
```json
{"url": "https://docs.rs/tokio/latest/tokio/"}
```
"""

[conversation.tools.web_fetch.style]
parameters = "function_call"
inline_results = "off"
results_file_link = "full"

[conversation.tools.web_fetch.parameters.url]
type = "string"
required = true
summary = "The URL of the web page to fetch."
