// Exposes the `jp_ffi` C entry points to Swift.
//
// `jp_ffi.h` is generated by `just build-ffi` into the cargo target directory,
// which the target's HEADER_SEARCH_PATHS points at.

#import "jp_ffi.h"
