import Foundation
import Testing

/// The suite every test that touches process-wide state belongs to.
///
/// Opening a workspace reads `JP_USER_DATA_DIR` from the environment, and the
/// recent-workspaces list is system state shared by the whole process. Neither
/// can be made per-test, so the tests that use them are serialized instead — and
/// serialized *together*, which is why they are nested here: `.serialized` orders
/// the tests within a suite, and sibling suites still run alongside each other.
///
/// Nesting from another file is what the `extension WorkspaceSuite` declarations
/// in the sibling test files are doing.
///
/// Tests that touch none of this — decoding, ordering, presentation — stay
/// outside and run in parallel.
@Suite("Workspace", .serialized)
struct WorkspaceSuite {}

/// Create a disposable directory tree for one test, and point user-local storage
/// inside it.
///
/// Paired with ``removeSandbox(_:)`` through `defer` rather than owned by an
/// object with a `deinit`: ARC may release such an object right after its last
/// mention, which can be before the awaited work that uses the directory runs,
/// deleting the fixture out from under the test.
///
/// Only safe to call from inside ``WorkspaceSuite``, because it writes the
/// environment the whole process shares. Use ``makeTemporaryDirectory()`` for a
/// directory without that constraint.
func makeSandbox() throws -> URL {
    let root = try makeTemporaryDirectory()

    // Keep the user-local conversation store, which opening a workspace creates,
    // inside this test's own directory rather than the real user data directory.
    setenv("JP_USER_DATA_DIR", root.appendingPathComponent("user-data").path, 1)
    unsetenv("XDG_DATA_HOME")

    return root
}

/// Create a disposable directory for one test.
///
/// Writes no environment and touches nothing outside itself, so it is safe from
/// any suite. Paired with ``removeSandbox(_:)``.
func makeTemporaryDirectory() throws -> URL {
    let root = URL(fileURLWithPath: NSTemporaryDirectory())
        .appendingPathComponent("jp-tests-\(UUID().uuidString)")
    try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
    return root
}

func removeSandbox(_ root: URL) {
    try? FileManager.default.removeItem(at: root)
}

/// Create a workspace root with an empty store, and return its path.
///
/// The workspace ID is written rather than left for JP to mint, because JP
/// derives one from the current millisecond: two workspaces created in the same
/// millisecond would share an ID, and with it the user-local store keyed by it.
func makeWorkspace(in root: URL, named name: String = "my-workspace") throws -> String {
    let workspace = root.appendingPathComponent(name)
    let store = workspace.appendingPathComponent(".jp")
    try FileManager.default.createDirectory(at: store, withIntermediateDirectories: true)

    // `Id::load` reads the last line, and rejects anything that is not five
    // characters of `[0-9a-z]`.
    let preamble = "DO NOT EDIT THIS FILE! IT IS AUTO-GENERATED BY JP."
    try "\(preamble)\n\(makeWorkspaceID())\n"
        .write(to: store.appendingPathComponent(".id"), atomically: true, encoding: .utf8)

    return workspace.path
}

/// Create a directory with no workspace in it, and return its path.
func makeBareDirectory(in root: URL, named name: String) throws -> String {
    let directory = root.appendingPathComponent(name)
    try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
    return directory.path
}

/// A workspace ID in the shape JP accepts: five characters of `[0-9a-z]`.
private func makeWorkspaceID() -> String {
    let alphabet = Array("0123456789abcdefghijklmnopqrstuvwxyz")
    return String((0..<5).map { _ in alphabet.randomElement() ?? "0" })
}
