use std::{env, fs, path::PathBuf};

use jp_config::{
    PartialAppConfig,
    conversation::compaction::{
        CompactionConfig, CompactionRuleConfig, PartialCompactionRuleConfig, PartialSummaryConfig,
        ReasoningMode, ToolCallsMode,
    },
};
use jp_conversation::{
    Compaction, CompactionRange, ConversationStream, ReasoningPolicy, SummaryOverlap,
    SummaryPolicy, SummarySource, ToolCallPolicy, compaction::extend_summary_range,
};
use jp_workspace::{ConversationHandle, ConversationMut, Workspace};
use tracing::warn;

use crate::{
    cmd::{
        ConversationLoadRequest, Output,
        conversation_id::PositionalIds,
        lock::{LockOutcome, LockRequest, acquire_lock},
        query::apply_model,
        turn_selection::{
            Bound, BoundWindow, TurnSelection, keep_first_bound, keep_last_bound, resolve_window,
        },
    },
    ctx::{Ctx, IntoPartialAppConfig},
    format::compaction_policy_label,
};

#[derive(Debug, clap::Args)]
pub(crate) struct Compact {
    #[command(flatten)]
    target: PositionalIds<true, true>,

    /// Which turns to compact.
    ///
    /// `--from`/`--to` bound the compacted range; `--first N`/`--last N`
    /// compact the first or last N turns (both together compact each window and
    /// skip the middle); `--turn N` compacts a single turn, or `--turn A..B` an
    /// inclusive range (e.g. `1..5` is turns 1-5).
    /// `--keep-first`/`--keep-last` protect turns at either end from whichever
    /// range is selected.
    #[command(flatten)]
    range: TurnSelection,

    /// Strip reasoning (thinking) blocks from the compacted range.
    #[arg(short, long, conflicts_with = "compact")]
    reasoning: bool,

    /// Strip tool call content from the compacted range.
    ///
    /// Used without a value, strips both requests and responses.
    /// Otherwise one of (with short aliases):
    ///
    /// - `strip` (`s`): strip request arguments and response content
    /// - `strip-requests` (`sreq`): strip request arguments only
    /// - `strip-responses` (`sres`): strip response content only
    /// - `omit` (`o`): remove tool call pairs entirely
    #[arg(
        short,
        long,
        value_parser = parse_tool_calls_mode,
        num_args = 0..=1,
        default_missing_value = "strip",
        conflicts_with = "compact",
    )]
    tools: Option<ToolCallsMode>,

    /// Replace the compacted turns with a summary.
    ///
    /// Without a value, the summary is generated by the assistant.
    /// With a value, that text is used verbatim and no model is called, e.g.
    /// `--summary "we settled on the layered loader"`.
    #[arg(short, long, conflicts_with = "compact")]
    summary: Option<Option<String>>,

    /// Extra guidance for the summarizer, e.g. "focus on the architecture".
    ///
    /// Rides on the summarization request as supplementary context; it adds to
    /// the summarizer's instructions rather than replacing them.
    /// Applies to every rule in this invocation that generates a summary,
    /// overriding any `conversation.compaction.rules[].summary.context` they
    /// set themselves.
    /// Has no effect on a verbatim `--summary TEXT`, which calls no model.
    #[arg(long)]
    summary_context: Option<String>,

    /// The model to summarize with.
    ///
    /// Accepts a model alias or a full `provider/name` ID, the same values as
    /// `jp query --model`.
    /// Overrides the summarizer model for every rule in this invocation,
    /// including rules that set their own
    /// `conversation.compaction.rules[].summary.model`.
    /// Only affects rules that generate a summary; without one, nothing calls
    /// an LLM.
    #[arg(short = 'm', long)]
    model: Option<String>,

    /// Preview what would change without applying.
    #[arg(long)]
    dry_run: bool,

    /// Remove compaction events from the stream.
    ///
    /// Without a value, removes every compaction event, restoring the raw event
    /// history so the LLM sees all original events.
    /// With a value (`--reset=2`), removes only that compaction event, numbered
    /// as `jp conversation show` lists them.
    /// Mutually exclusive with the policy, range, and DSL flags: `--reset`
    /// undoes compaction, it does not re-compact in the same invocation.
    /// Composes with `--dry-run` to preview the removal.
    #[arg(
        long,
        value_name = "INDEX",
        require_equals = true,
        value_parser = parse_compaction_index,
        conflicts_with_all = [
            "keep_first", "keep_last", "from", "to", "first", "last", "turn",
            "reasoning", "tools", "summary", "summary_context", "compact", "model",
        ],
    )]
    reset: Option<Option<usize>>,

    /// Compact using an inline DSL rule.
    ///
    /// Mutually exclusive with the dedicated `--reasoning`/`--tools`/
    /// `--summary` flags above: use either the flags or the DSL, not both.
    /// See `jp query --help` for DSL syntax.
    #[command(flatten)]
    compact_flag: crate::cmd::compact_flag::CompactFlag,
}

impl Compact {
    /// Returns `true` if any dedicated policy flag is set.
    ///
    /// Policy flags (`--reasoning`/`--tools`/`--summary`) build a single ad-hoc
    /// rule.
    /// Range flags (`--keep-first`/`--keep-last`/`--from`/`--to`) are
    /// deliberately excluded: they are applied at runtime as range overrides on
    /// the active rules, not as a rule of their own.
    /// `--summary-context` and `--model` are excluded for the same reason: they
    /// modify whichever rules end up active rather than defining one.
    fn has_policy_overrides(&self) -> bool {
        self.reasoning || self.tools.is_some() || self.summary.is_some()
    }
}

impl Compact {
    /// Resolve the effective compaction rules for this invocation.
    ///
    /// Dedicated policy flags (`--reasoning`/`--tools`/`--summary`) build one
    /// ad-hoc rule; inline DSL specs (`-k SPEC`) each build one. clap makes the
    /// two mutually exclusive (the policy flags `conflicts_with` the `compact`
    /// flag), so at most one side is ever populated.
    /// These explicit rules replace the configured rules, unless a bare
    /// `--compact` is also present, in which case they are appended to the
    /// configured rules.
    ///
    /// Range flags (`--keep-first`/`--keep-last`/`--from`/`--to`) are NOT
    /// rules: `compact_one` applies them as range overrides on whichever rules
    /// end up active (see `resolve_from`/`resolve_to`), so a range-only
    /// invocation narrows the configured rules instead of replacing them with a
    /// policy-less no-op.
    fn effective_rules(
        &self,
        cfg: &jp_config::AppConfig,
    ) -> Result<Vec<CompactionRuleConfig>, jp_config::ConfigError> {
        let mut explicit: Vec<PartialCompactionRuleConfig> = Vec::new();

        if self.has_policy_overrides() {
            let mut rule = PartialCompactionRuleConfig::default();
            if self.reasoning {
                rule.reasoning = Some(ReasoningMode::Strip);
            }
            rule.tool_calls = self.tools;
            if let Some(text) = &self.summary {
                rule.summary = Some(PartialSummaryConfig {
                    text: text.clone(),
                    ..PartialSummaryConfig::default()
                });
            }
            explicit.push(rule);
        }

        explicit.extend(self.compact_flag.dsl_rules());

        let explicit = CompactionConfig::finalize_rules(explicit)?;
        let mut rules = crate::cmd::compact_flag::combine_rules(
            &cfg.conversation.compaction.rules,
            self.compact_flag.use_config_rules,
            explicit,
        );

        if self.model.is_some() {
            redirect_summaries_to_assistant_model(&mut rules, cfg);
        }

        if let Some(context) = &self.summary_context {
            for summary in rules.iter_mut().filter_map(|rule| rule.summary.as_mut()) {
                summary.context = Some(context.clone());
            }
        }

        Ok(rules)
    }
}

/// Point every rule that names its own summary model at `assistant.model.id`.
///
/// A rule with no `summary.model` already summarizes on the assistant model, so
/// it needs nothing here.
/// A rule that names one would otherwise outrank `--model`, which is applied to
/// `assistant.model`.
/// Only the ID moves: the rule keeps its own summary parameters (max tokens,
/// temperature, ...).
fn redirect_summaries_to_assistant_model(
    rules: &mut [CompactionRuleConfig],
    cfg: &jp_config::AppConfig,
) {
    for summary in rules.iter_mut().filter_map(|rule| rule.summary.as_mut()) {
        if let Some(model) = summary.model.as_mut() {
            model.id = cfg.assistant.model.id.clone();
        }
    }
}

impl IntoPartialAppConfig for Compact {
    fn apply_cli_config(
        &self,
        _: Option<&Workspace>,
        mut partial: PartialAppConfig,
        merged_config: Option<&PartialAppConfig>,
    ) -> std::result::Result<PartialAppConfig, Box<dyn std::error::Error + Send + Sync>> {
        apply_model(&mut partial, self.model.as_deref(), merged_config);

        Ok(partial)
    }
}

fn parse_tool_calls_mode(s: &str) -> Result<ToolCallsMode, String> {
    s.parse().map_err(|_| {
        "expected one of: strip (s), strip-requests (sreq), strip-responses (sres), omit (o)"
            .to_string()
    })
}

/// Parse the `--reset=INDEX` value: a 1-based position among the conversation's
/// compaction events.
fn parse_compaction_index(s: &str) -> Result<usize, String> {
    match s.parse() {
        Ok(0) => Err("compaction indices are 1-based; `0` is not a valid index".to_owned()),
        Ok(n) => Ok(n),
        Err(_) => Err(format!("invalid compaction index '{s}'")),
    }
}

/// Look up the compaction event a 1-based `--reset=INDEX` addresses.
///
/// Returns its 0-based position among the stream's compaction events, plus a
/// `turns X..Y` label for the removal message (turn numbers 1-based, as the
/// user sees them elsewhere).
/// An index naming no event is an error rather than a silent no-op, matching
/// how `--turn` treats an out-of-range turn.
fn resolve_reset_index(
    events: &ConversationStream,
    index: usize,
) -> Result<(usize, String), String> {
    let Some(position) = index.checked_sub(1) else {
        return Err("compaction indices are 1-based; `0` is not a valid index".to_owned());
    };

    let Some(compaction) = events.compactions().nth(position) else {
        let count = events.compactions().count();
        return Err(format!(
            "compaction {index} out of range (conversation has {count} compaction event(s))"
        ));
    };

    Ok((
        position,
        format!(
            "turns {}..{}",
            compaction.from_turn + 1,
            compaction.to_turn + 1
        ),
    ))
}

/// Resolve the turn range a single rule would compact within one selected
/// window.
///
/// `range_stream` is the baseline for resolving bounds, including
/// `AfterLastCompaction` (`--from last-compaction`): it must be the stream as
/// it existed at the start of the invocation, so every rule resolves it against
/// the same compactions and a rule generated earlier in the same invocation
/// doesn't shift the baseline for a later one.
///
/// `overlap_stream` is consulted only to extend summary ranges over partially
/// overlapping summaries; it accumulates the compactions generated so far in
/// this invocation so two summary rules can't be appended unextended.
///
/// For non-summary rules the two streams are interchangeable (only
/// `extend_summary_range` reads `overlap_stream`).
/// Shared by the dry-run preview and the real build so they always agree.
///
/// `Ok(None)` means the rule selects no turns.
///
/// # Errors
///
/// Returns the [`SummaryOverlap`] when the range would have to grow over a
/// verbatim summary, or a verbatim summary's range would have to grow.
fn resolve_rule_range(
    range_stream: &ConversationStream,
    overlap_stream: &ConversationStream,
    rule: &CompactionRuleConfig,
    window: &BoundWindow,
    selection: &TurnSelection,
) -> Result<Option<CompactionRange>, SummaryOverlap> {
    // The rule's own `keep_first`/`keep_last` fills a side the selection left
    // open, unless the matching CLI keep flag is set: an explicit
    // `--keep-first` replaces the configured bound rather than stacking on top
    // of it.
    let from = match (&window.from, selection.keep_first()) {
        (Bound::Default, None) => keep_first_bound(&rule.keep_first, range_stream),
        (side, _) => side.clone(),
    };
    let to = match (&window.to, selection.keep_last()) {
        (Bound::Default, None) => keep_last_bound(&rule.keep_last, range_stream),
        (side, _) => side.clone(),
    };

    let Some(resolved) = resolve_window(&BoundWindow { from, to }, range_stream) else {
        return Ok(None);
    };
    let Some(trimmed) = selection.trim(resolved, range_stream) else {
        return Ok(None);
    };
    let range = CompactionRange {
        from_turn: trimmed.from,
        to_turn: trimmed.to,
    };

    match rule_summary_source(rule) {
        Some(source) => extend_summary_range(overlap_stream, range, source).map(Some),
        None => Ok(Some(range)),
    }
}

/// The provenance of the summary this rule would produce, or `None` when it
/// produces no summary.
fn rule_summary_source(rule: &CompactionRuleConfig) -> Option<SummarySource> {
    rule.summary.as_ref().map(|summary| {
        if summary.text.is_some() {
            SummarySource::Authored
        } else {
            SummarySource::Generated
        }
    })
}

/// Resolve every selected window into the ranges one rule will compact.
///
/// A summary rule's range grows to subsume any summary it touches
/// ([`extend_summary_range`]), so two windows that started out disjoint can
/// extend onto each other — or onto the same pre-existing summary — and end
/// up overlapping or identical.
/// Coalescing here, before any text is generated, keeps one region from being
/// compacted twice and one summary from being generated only to be immediately
/// superseded by the next.
///
/// Sorting by start turn first makes a single left-to-right sweep enough:
/// extending the open range as it goes absorbs transitive chains (A touches B,
/// B touches C) without a second pass.
///
/// # Errors
///
/// Returns the [`SummaryOverlap`] when a window's range would have to grow over
/// a verbatim summary, or a verbatim summary's range would have to grow.
fn plan_rule_ranges(
    range_stream: &ConversationStream,
    overlap_stream: &ConversationStream,
    rule: &CompactionRuleConfig,
    windows: &[BoundWindow],
    selection: &TurnSelection,
) -> Result<Vec<CompactionRange>, SummaryOverlap> {
    let mut ranges = Vec::with_capacity(windows.len());
    for window in windows {
        if let Some(range) =
            resolve_rule_range(range_stream, overlap_stream, rule, window, selection)?
        {
            ranges.push(range);
        }
    }

    ranges.sort_by_key(|r| (r.from_turn, r.to_turn));

    let mut merged: Vec<CompactionRange> = Vec::with_capacity(ranges.len());
    for range in ranges {
        match merged.last_mut() {
            // Intersection only: two abutting ranges are distinct regions, and
            // for a summary rule two adjacent summaries are legal.
            Some(last) if range.from_turn <= last.to_turn => {
                last.to_turn = last.to_turn.max(range.to_turn);
            }
            _ => merged.push(range),
        }
    }

    Ok(merged)
}

/// Reject a verbatim summary whose text is blank.
///
/// The generated path refuses an empty model response rather than let it
/// replace the turns it stands for; verbatim text is held to the same bar,
/// whether it came from `--summary ""` or a blank `summary.text`.
///
/// Shared by the dry-run preview and the real build so a preview never promises
/// a compaction the run would reject.
fn validate_summary_text(rule: &CompactionRuleConfig) -> crate::Result<()> {
    let Some(text) = rule.summary.as_ref().and_then(|s| s.text.as_deref()) else {
        return Ok(());
    };

    if text.trim().is_empty() {
        return Err(crate::error::Error::Compaction(
            "the summary text is empty; drop the value to generate a summary instead".to_owned(),
        ));
    }

    Ok(())
}

/// Report an unresolvable summary overlap in the 1-based turn numbers the user
/// typed.
fn overlap_error(overlap: &SummaryOverlap) -> crate::error::Error {
    crate::error::Error::SummaryOverlap {
        authored: overlap.new_is_authored,
        from: overlap.requested.from_turn + 1,
        to: overlap.requested.to_turn + 1,
        required_from: overlap.required.from_turn + 1,
        required_to: overlap.required.to_turn + 1,
    }
}

/// Resolve the summary text (if any) and assemble a [`Compaction`] for an
/// already-resolved range.
///
/// A rule carrying `summary.text` is satisfied without contacting a provider.
/// Otherwise the summarizer reads the raw events in `events` for the range.
async fn build_compaction_for_range(
    events: &ConversationStream,
    cfg: &jp_config::AppConfig,
    rule: &CompactionRuleConfig,
    range: CompactionRange,
    printer: Option<&jp_printer::Printer>,
) -> crate::Result<Compaction> {
    validate_summary_text(rule)?;

    let compaction = build_mechanical_compaction(range.from_turn, range.to_turn, rule);

    let Some(summary) = rule.summary.as_ref() else {
        return Ok(compaction);
    };

    if let Some(text) = summary.text.as_deref() {
        return Ok(compaction.with_summary(SummaryPolicy::authored(text)));
    }

    if let Some(printer) = printer {
        printer.println("Generating summary...");
    }

    let text = super::summarize::generate_summary(
        events,
        range.from_turn,
        range.to_turn,
        Some(summary),
        cfg,
    )
    .await?;

    Ok(compaction.with_summary(SummaryPolicy::generated(text)))
}

/// Build compaction events from the given resolved rules.
///
/// Each rule produces one `Compaction` event per selected window, so a disjoint
/// selection (`--first N --last M`) compacts each window separately and leaves
/// the turns between them untouched.
///
/// Every range is resolved and every deterministic check runs before the first
/// summarizer request, so a rule that turns out to be unsatisfiable cannot
/// strand a paid request made for an earlier one.
pub(crate) async fn build_compaction_events(
    events: &ConversationStream,
    cfg: &jp_config::AppConfig,
    rules: &[CompactionRuleConfig],
    selection: &TurnSelection,
    printer: Option<&jp_printer::Printer>,
) -> crate::Result<Vec<Compaction>> {
    let plan = plan_compactions(events, rules, selection)?;

    let mut compactions = Vec::with_capacity(plan.len());
    for (rule, range) in plan {
        compactions.push(build_compaction_for_range(events, cfg, rule, range, printer).await?);
    }

    Ok(compactions)
}

/// Resolve the ranges each rule would compact, in order, rejecting anything the
/// build would reject.
///
/// Rules that select no turns contribute nothing rather than being reported.
///
/// Two distinct baselines:
///
/// - Range resolution uses the original `events` for every rule, so
///   `AfterLastCompaction` (`--from last-compaction` / `keep_first =
///   "last-compaction"`) resolves against the compactions present at invocation
///   start and applies uniformly, rather than each rule starting after the
///   previous rule's freshly generated compaction.
/// - `overlap` accumulates the compactions planned so far, so a later summary
///   rule's overlap extension sees earlier summaries in this same invocation
///   and can't be appended unextended.
///
/// # Errors
///
/// Returns the first unresolvable summary overlap, or the first blank verbatim
/// summary.
fn plan_compactions<'a>(
    events: &ConversationStream,
    rules: &'a [CompactionRuleConfig],
    selection: &TurnSelection,
) -> crate::Result<Vec<(&'a CompactionRuleConfig, CompactionRange)>> {
    let windows = selection.windows(events);
    let mut overlap = events.clone();
    let mut plan = Vec::new();

    for rule in rules {
        let ranges = plan_rule_ranges(events, &overlap, rule, &windows, selection)
            .map_err(|conflict| overlap_error(&conflict))?;

        if ranges.is_empty() {
            continue;
        }

        validate_summary_text(rule)?;

        for range in ranges {
            // Only the range and the provenance affect how a later rule
            // resolves, so a placeholder stands in for the compaction this rule
            // will produce.
            if let Some(source) = rule_summary_source(rule) {
                overlap.add_compaction(
                    Compaction::new(range.from_turn, range.to_turn).with_summary(SummaryPolicy {
                        summary: String::new(),
                        source,
                    }),
                );
            }

            plan.push((rule, range));
        }
    }

    Ok(plan)
}

/// Apply compaction events to the conversation stream.
///
/// Mutation only: callers that want to report the result render their own
/// timeline (see [`timeline_lines`]).
/// The `jp query --compact` path applies silently so compaction details don't
/// clutter the query output.
pub(crate) fn apply_compactions(conv: &ConversationMut, compactions: Vec<Compaction>) {
    for compaction in compactions {
        conv.update_events(|stream| stream.add_compaction(compaction));
    }
}

/// A compacted range plus a short label describing what was done to it.
///
/// `label` is `None` only for a (degenerate) compaction with no policy.
struct TimelineSegment {
    from: usize,
    to: usize,
    label: Option<String>,
    /// Whether this range was already compacted before this invocation.
    ///
    /// Existing compactions are reported factually ("Compacted") even under
    /// `--dry-run`, since they pre-date the previewed run.
    existing: bool,
}

/// Build timeline segments for the compactions about to be applied, spilling
/// each summary to a temp file so the timeline can link to it.
///
/// `conv_id` prefixes the temp-file names so summaries from different
/// conversations don't collide.
fn segments_for_compactions(compactions: &[Compaction], conv_id: &str) -> Vec<TimelineSegment> {
    compactions
        .iter()
        .map(|c| {
            let label = match &c.summary {
                Some(summary) => {
                    let kind = summary_label(summary.source);
                    Some(
                        match write_summary_file(conv_id, c.from_turn, c.to_turn, &summary.summary)
                        {
                            Some(path) => format!("{kind}: {}", path.display()),
                            None => kind.to_owned(),
                        },
                    )
                }
                None => compaction_policy_label(c),
            };
            TimelineSegment {
                from: c.from_turn,
                to: c.to_turn,
                label,
                existing: false,
            }
        })
        .collect()
}

/// The timeline word for a summary of this provenance.
///
/// Verbatim text is called out so a reader scanning the timeline can tell which
/// ranges stand behind their own words and which behind the model's.
const fn summary_label(source: SummarySource) -> &'static str {
    match source {
        SummarySource::Generated => "summary",
        SummarySource::Authored => "verbatim summary",
    }
}

/// Build timeline segments for compactions already present at invocation start.
///
/// Without these, the turns they cover would be reported as kept even though
/// the projected conversation still compacts them (most visibly with `--from
/// last`, which starts the new range after the existing compactions).
fn existing_segments(snapshot: &ConversationStream) -> Vec<TimelineSegment> {
    snapshot
        .compactions()
        .map(|c| TimelineSegment {
            from: c.from_turn,
            to: c.to_turn,
            label: Some("already compacted".to_owned()),
            existing: true,
        })
        .collect()
}

/// Write a generated summary to a temp file so the timeline can link to it.
///
/// The summary is also stored durably in the conversation stream; this file is
/// a convenience copy for immediate viewing.
/// Returns `None` (and logs) when the write fails — a missing convenience file
/// must not abort compaction.
fn write_summary_file(conv_id: &str, from: usize, to: usize, summary: &str) -> Option<PathBuf> {
    let path = env::temp_dir().join(format!("{conv_id}-summary-{from}-{to}.md"));
    match fs::write(&path, summary) {
        Ok(()) => Some(path),
        Err(err) => {
            warn!(%err, path = %path.display(), "Failed to write summary file.");
            None
        }
    }
}

/// Build the interleaved kept/compacted timeline lines for one invocation.
///
/// Compactions are sorted by start turn; a kept line is emitted for each gap
/// before, between, and after the compacted ranges.
/// Overlapping ranges collapse naturally — a gap is printed only where no
/// compaction covers it.
/// `dry_run` switches the verbs from "Compacted"/"Kept" to "Would have
/// compacted"/"Would have kept", except for segments already compacted before
/// this run, which always read "Compacted".
fn timeline_lines(segments: &[TimelineSegment], last_turn: usize, dry_run: bool) -> Vec<String> {
    let kept = if dry_run { "Would have kept" } else { "Kept" };

    let mut ordered: Vec<&TimelineSegment> = segments.iter().collect();
    ordered.sort_by_key(|s| s.from);

    let mut lines = Vec::new();
    // Highest turn covered by a compaction so far; `None` before the first.
    let mut covered: Option<usize> = None;
    for segment in ordered {
        let next_kept = covered.map_or(0, |c| c + 1);
        if segment.from > next_kept {
            lines.push(kept_line(kept, next_kept, segment.from - 1));
        }

        // Pre-existing compactions are factual even under `--dry-run`; only this
        // run's new compactions are hypothetical.
        let compacted = if dry_run && !segment.existing {
            "Would have compacted"
        } else {
            "Compacted"
        };

        let count = segment.to - segment.from + 1;
        // Stored indices are 0-based; turn numbers shown to the user are 1-based.
        lines.push(match &segment.label {
            Some(label) => format!(
                "{compacted} turns {}..{} ({count} total, {label}).",
                segment.from + 1,
                segment.to + 1,
            ),
            None => format!(
                "{compacted} turns {}..{} ({count} total).",
                segment.from + 1,
                segment.to + 1,
            ),
        });

        covered = Some(covered.map_or(segment.to, |c| c.max(segment.to)));
    }

    let tail = covered.map_or(0, |c| c + 1);
    if tail <= last_turn {
        lines.push(kept_line(kept, tail, last_turn));
    }

    lines
}

/// Format a single kept line for the inclusive range `[from, to]`.
fn kept_line(verb: &str, from: usize, to: usize) -> String {
    // Stored indices are 0-based; turn numbers shown to the user are 1-based.
    if from == to {
        format!("{verb} turn {}.", from + 1)
    } else {
        format!("{verb} turns {}..{}.", from + 1, to + 1)
    }
}

/// Build a `Compaction` event from mechanical policies (no summary).
fn build_mechanical_compaction(
    from_turn: usize,
    to_turn: usize,
    rule: &CompactionRuleConfig,
) -> Compaction {
    let mut compaction = Compaction::new(from_turn, to_turn);

    if rule.reasoning.is_some() {
        compaction = compaction.with_reasoning(ReasoningPolicy::Strip);
    }

    if let Some(mode) = rule.tool_calls {
        compaction = compaction.with_tool_calls(match mode {
            ToolCallsMode::Strip => ToolCallPolicy::Strip {
                request: true,
                response: true,
            },
            ToolCallsMode::StripResponses => ToolCallPolicy::Strip {
                request: false,
                response: true,
            },
            ToolCallsMode::StripRequests => ToolCallPolicy::Strip {
                request: true,
                response: false,
            },
            ToolCallsMode::Omit => ToolCallPolicy::Omit,
        });
    }

    compaction
}

impl Compact {
    pub(crate) fn conversation_load_request(&self) -> ConversationLoadRequest {
        ConversationLoadRequest::explicit_or_session(&self.target)
    }

    pub(crate) async fn run(self, ctx: &mut Ctx, handles: Vec<ConversationHandle>) -> Output {
        self.range.validate()?;

        // Reject an out-of-range `--turn` against every target before compacting
        // any of them, so a bad endpoint on the last conversation can't leave the
        // earlier ones already compacted.
        // `compact_one` re-checks against the locked snapshot, which is the
        // authoritative count if a concurrent writer appends in between.
        for handle in &handles {
            self.range
                .check_turn_range(ctx.workspace.events(handle)?.turn_count())?;
        }

        for handle in handles {
            self.compact_one(ctx, handle).await?;
        }
        Ok(())
    }

    async fn compact_one(&self, ctx: &mut Ctx, handle: ConversationHandle) -> Output {
        let lock = match acquire_lock(LockRequest::from_ctx(handle, ctx)).await? {
            LockOutcome::Acquired(lock) => lock,
            LockOutcome::NewConversation | LockOutcome::ForkConversation(_) => {
                unreachable!("compact does not allow new/fork on contention")
            }
        };

        let cfg = ctx.config();
        let mut conv = lock.into_mut();
        let events_snapshot = conv.events().clone();

        if let Some(index) = self.reset {
            return self.run_reset(ctx, conv, &events_snapshot, index);
        }

        self.range.check_turn_range(events_snapshot.turn_count())?;

        // The effective rules combine the configured rules with any policy
        // flags / inline DSL (replace, or append under bare `--compact`).
        let rules = self
            .effective_rules(&cfg)
            .map_err(|e| crate::error::Error::Compaction(e.to_string()))?;

        if self.dry_run {
            return Self::preview_compaction(ctx, &events_snapshot, &rules, &self.range);
        }

        let compactions = build_compaction_events(
            &events_snapshot,
            &cfg,
            &rules,
            &self.range,
            Some(&ctx.printer),
        )
        .await?;

        if compactions.is_empty() {
            ctx.printer.println("Nothing to compact.");
            return Ok(());
        }

        let last_turn = events_snapshot.turn_count().saturating_sub(1);
        // Carry the pre-existing compactions so their turns aren't reported as
        // kept; the projected conversation still compacts them.
        let mut segments = existing_segments(&events_snapshot);
        segments.extend(segments_for_compactions(
            &compactions,
            &conv.id().to_string(),
        ));
        apply_compactions(&conv, compactions);
        // Write before reporting the timeline, so a failed write is an error
        // rather than a confirmation the user cannot trust.
        conv.flush()?;
        for line in timeline_lines(&segments, last_turn, false) {
            ctx.printer.println(line);
        }

        Ok(())
    }

    /// Handle `--reset[=INDEX]`: remove every compaction event, or just the one
    /// at `index` (1-based, in stream order).
    ///
    /// Under `--dry-run` nothing is mutated and the message describes what
    /// would be removed.
    /// An `index` past the last compaction event is an error rather than a
    /// silent no-op (matching `--turn`).
    fn run_reset(
        &self,
        ctx: &Ctx,
        conv: ConversationMut,
        events: &ConversationStream,
        index: Option<usize>,
    ) -> Output {
        let Some(index) = index else {
            let count = if self.dry_run {
                events.compactions().count()
            } else {
                conv.update_events_and_flush(ConversationStream::remove_compactions)?
            };

            ctx.printer.println(match (count, self.dry_run) {
                (0, _) => "No compaction events to remove.".to_owned(),
                (count, true) => format!("Would remove {count} compaction event(s)."),
                (count, false) => format!("Removed {count} compaction event(s)."),
            });
            return Ok(());
        };

        let (position, range) = resolve_reset_index(events, index)?;

        if self.dry_run {
            ctx.printer
                .println(format!("Would remove compaction {index} ({range})."));
            return Ok(());
        }

        conv.update_events_and_flush(|stream| stream.remove_compaction(position))?;
        ctx.printer
            .println(format!("Removed compaction {index} ({range})."));

        Ok(())
    }

    /// Preview the compaction timeline without mutating the conversation.
    ///
    /// Resolves the same per-rule ranges as the real run (minus the summarizer
    /// and the mutation), then prints the dry-run timeline.
    /// Summary rules show a bare label since no text is generated in a preview.
    /// An overlap that the real run would refuse is refused here too, so a
    /// preview never promises a compaction the run cannot perform.
    fn preview_compaction(
        ctx: &Ctx,
        events_snapshot: &ConversationStream,
        rules: &[CompactionRuleConfig],
        selection: &TurnSelection,
    ) -> Output {
        // Range resolution uses the original snapshot for every rule, while
        // `overlap` accumulates this run's summaries so later summary rules
        // preview the same (possibly extended) ranges as the real run.
        let windows = selection.windows(events_snapshot);
        let mut overlap = events_snapshot.clone();
        let mut new_segments = Vec::new();
        for rule in rules {
            let ranges = plan_rule_ranges(events_snapshot, &overlap, rule, &windows, selection)
                .map_err(|conflict| overlap_error(&conflict))?;

            if ranges.is_empty() {
                continue;
            }

            // Checked after the ranges resolve so a rule that selects no turns
            // is skipped here exactly as it is in the real run, which never
            // reaches `build_compaction_for_range` for it.
            validate_summary_text(rule)?;

            let source = rule_summary_source(rule);
            for range in ranges {
                let label = match source {
                    Some(source) => Some(summary_label(source).to_owned()),
                    None => compaction_policy_label(&build_mechanical_compaction(
                        range.from_turn,
                        range.to_turn,
                        rule,
                    )),
                };
                new_segments.push(TimelineSegment {
                    from: range.from_turn,
                    to: range.to_turn,
                    label,
                    existing: false,
                });
                // The placeholder carries the rule's provenance so a second
                // summary rule previews the same refusal the real run would
                // produce.
                if let Some(source) = source {
                    overlap.add_compaction(
                        Compaction::new(range.from_turn, range.to_turn).with_summary(
                            SummaryPolicy {
                                summary: String::new(),
                                source,
                            },
                        ),
                    );
                }
            }
        }

        if new_segments.is_empty() {
            ctx.printer.println("Nothing to compact.");
            return Ok(());
        }

        // Prepend the pre-existing compactions so already-compacted turns aren't
        // previewed as kept; the projected conversation still compacts them.
        let mut segments = existing_segments(events_snapshot);
        segments.extend(new_segments);

        let last_turn = events_snapshot.turn_count().saturating_sub(1);
        for line in timeline_lines(&segments, last_turn, true) {
            ctx.printer.println(line);
        }

        Ok(())
    }
}

#[cfg(test)]
#[path = "compact_tests.rs"]
mod tests;
