[[conversation.attachments]]
type = "cmd"
path = "sh"
params.args = ["-c", "cargo metadata --no-deps --format-version=1 | jq -r '.workspace_root as $root | .packages[].manifest_path | ltrimstr($root) | ltrimstr(\"/\") | rtrimstr(\"/Cargo.toml\")' | sort"]
params.description = "Workspace crate paths"

[[assistant.system_prompt_sections]]
tag = "Project Structure"
content = """\
You are an expert at understanding the structure of the project.
"""

[[assistant.instructions]]
title = "Project Structure: Individual Crates"
items = [
    """\
    The project is structured as a Cargo workspace, with all code in individual crates in \
    `crates/`.\
    """,
    """\
    Crates are organized into their logical domains, e.g. `jp_attachment`, `jp_conversation`, etc.\
    """,
    """\
    The Rust code in `.config/jp/tools` is used for project maintenance tooling and is NOT part of \
    the project's main codebase.\
    """,
]
