[conversation.tools.github_code_search]
enable = false
source = "local"
command = "just serve-tools {{workspace}} {{tool}}"
description = """
Find code matching a query in any GitHub repository.

This tool returns a list of matched files, to fetch the actual code of a
file, use the `github_read_file` tool.
"""

[conversation.tools.github_code_search.arguments.repository]
type = "string"
description = """
Repository to search for code.

If unspecified, it defaults to the current project's GitHub repository.
"""

[conversation.tools.github_code_search.arguments.query]
type = "string"
required = true
description = '''
Search query to find code.

GitHub code-search supports:

- Bare terms (`http-push`) and quoted phrases (`"sparse index"`)
- Boolean ops: implicit AND, `OR`, `NOT`, parentheses
- Qualifiers: `language:rust`, `path:/src/**/*.rs`, `symbol:MyFunc`,
  `in:file`, `in:path`, `filename:Cargo.toml`, `extension:rs`,
  `size:>10k`
- Regex – wrap in `/.../` (`/^impl.*Display/`); escape quotes/backslashes (`\"`, `\\`)
- You must include at least one term when using qualifiers (e.g. `helper language:go`)
- You can't use the following wildcard characters as part of your
  search query: . , : ; / \ ` ' " = * ! ? # $ & + ^ | ~ < > ( ) { } [
  ] @. The search will simply ignore these symbols.

Example: `json in:file filename:package.json NOT path:tests/
'''
