[conversation.tools.github_pulls]
source = "local"
command = "just serve-tools {{workspace}} {{tool}}"
description = "Find one or more pull requests in the project's GitHub repository."

[conversation.tools.github_pulls.arguments.number]
type = "integer"
description = """
Pull request number to get information about.

If unspecified, a list of all pull requests will be returned, without the
pull request contents. You can re-run the tool with the correct pull request
number to get more details about a pull request.
"""

[conversation.tools.github_pulls.arguments.state]
type = "string"
enum = ["open", "closed"]
description = """
Filter pull requests by their state.

If unspecified, all pull requests will be returned.
"""

[conversation.tools.github_pulls.arguments.file_diffs]
type = "array"
items.type = "string"
description = """
List of changed file paths to get the diff for.

If unspecified, only the list of changed files will be returned, but not the
actual diff. You can re-run the tool with the correct file path to get the
diff.
"""
