[conversation.tools.github_read_file]
enable = false
source = "local"
command = "just serve-tools {{context}} {{tool}}"
summary = "Fetch the contents of one or more files"

examples = """
Read a file from the default branch:
```json
{"path": "Cargo.toml"}
```

Read from a specific branch in another repository:
```json
{"path": "src/main.rs", "ref": "develop", "repository": "owner/repo"}
```
"""

[conversation.tools.github_read_file.style]
inline_results = "off"
results_file_link = "off"
parameters = "function_call"

[conversation.tools.github_read_file.parameters.repository]
type = "string"
summary = "Repository to search for code."
description = """
If unspecified, it defaults to the current project's GitHub repository.
"""

[conversation.tools.github_read_file.parameters.path]
type = "string"
required = true
summary = "File path to get contents of."

[conversation.tools.github_read_file.parameters.ref]
type = "string"
summary = "The name of the commit/branch/tag."
description = '''
If unspecified, it defaults to the repository's default branch (usually `main`)
'''
