[conversation.tools.fs_delete_file]
enable = false
source = "local"
command = "just serve-tools {{context}} {{tool}}"
description = """
Delete a file in the project's local filesystem.

The file must exist, be a regular file, and have no uncommitted changes.
"""

[conversation.tools.fs_delete_file.parameters.path]
type = "string"
required = true
description = """
The path to the file to delete. The path must be relative to the project's root.
"""
