[conversation.tools.fs_grep_files]
enable = false
run = "always"
style.inline_results = "off"

source = "local"
command = "just serve-tools {{context}} {{tool}}"
description = """
Grep files in the project's local filesystem.

If misused, this tool can return *A LOT* of matches, making it difficult to
parse the results. It is recommended to use search patterns that are as specific
as possible to the content you are looking for.

If the number of results exceeds 100, the `context` option is disabled, and 50
matches are returned without context. You can re-run the tool with a more
specific pattern or limited to specific paths to narrow down the results with
context.
"""

[conversation.tools.fs_grep_files.parameters.pattern]
type = "string"
required = true
description = """
Regular expression to filter the results by.
"""

[conversation.tools.fs_grep_files.parameters.context]
type = "integer"
default = 0
description = """
Number of lines of context to include before and after the matching lines.
"""

[conversation.tools.fs_grep_files.parameters.paths]
type = "array"
items.type = "string"
description = """
Optional list of files or directories to search.

If unspecified, all files in the project will be returned.
"""
