//! MCP Host adapter for tool calls through JP's loopback HTTP endpoint.
//!
//! [`TerminalExecutorSource`] owns the endpoint, the Host's MCP connection, and
//! the task that routes the service's private interactions back to the tool
//! call that submitted them.
//! Each [`ToolExecutor`] drives one logical call: it holds the single-use Host
//! reply the service is waiting on, and hands the coordinator an
//! [`ExecutorResult`] whenever the call produces something the conversation
//! should record.

use std::{
    collections::HashMap,
    mem,
    sync::{
        Arc, Mutex as SyncMutex, MutexGuard, PoisonError,
        atomic::{AtomicBool, Ordering},
    },
    time::Duration,
};

use async_trait::async_trait;
use camino::Utf8PathBuf;
use futures::future::BoxFuture;
use indexmap::IndexMap;
use jp_config::conversation::tool::{RunMode, ToolConfigWithDefaults, ToolsConfig};
use jp_conversation::event::{InquirySource, ToolCallRequest, ToolCallResponse};
use jp_llm::query::ToolExecution;
use jp_mcp::{
    Client,
    server::{
        StderrSink,
        builtin::BuiltinExecutors,
        fan_out::{self, Split},
        http::{Endpoint, EndpointError},
        result::from_mcp,
        service::{
            AccessPolicyError, Admission, ConfiguredTool, Formatted, HostReply, HostRequest,
            InputAnswer, Interaction, InvocationId, Progress, Recording, ReleaseDecision, Service,
        },
    },
};
use jp_tool::{
    ContentBlock, InputRequest, InvocationContext, Question, QuestionId, ToolDefinition, ToolResult,
};
use rand::random;
use rmcp::{
    Peer, ServiceError as McpCallError,
    model::{CallToolRequestParams, Meta},
    service::{RoleClient, RunningService},
};
use serde_json::{Map, Value};
use tokio::{
    sync::{Mutex, Notify, broadcast, broadcast::error::RecvError as ProgressError, mpsc, oneshot},
    task::JoinHandle,
    time::timeout,
};
use tokio_util::sync::CancellationToken;
use tracing::{debug, warn};
use url::Url;

use super::executor::{
    CallExecutors, Executor, ExecutorError, ExecutorResult, ExecutorSource, FanOutCall,
    PermissionInfo, Review, response,
};
use crate::access::{approvals::ApprovalStore, compile::compile_tool_policy};

/// Where a call's correlation key travels on its MCP request when JP submits it
/// itself.
///
/// The value is generated by the Host and never derived from anything a caller
/// supplies, so a third-party MCP client cannot name someone else's call.
const CORRELATION_KEY: &str = "computer.jp/hostCall";

/// How long an announced agent call may take to reach the endpoint.
///
/// The announcement and the MCP request travel on independent transports, so
/// either can arrive first; this bounds the wait for the one that is late.
const AGENT_CALL_TIMEOUT: Duration = Duration::from_secs(30);

/// How many unroutable agent requests the router holds while their
/// announcements catch up.
const DEFERRED_LIMIT: usize = 64;

type Reply<T> = oneshot::Sender<HostReply<T>>;

fn locked<T>(value: &SyncMutex<T>) -> MutexGuard<'_, T> {
    // No caller code runs under these locks, so recovering a poisoned one lets
    // an unrelated panic elsewhere finish this turn's calls rather than hang
    // them.
    value.lock().unwrap_or_else(PoisonError::into_inner)
}

/// The value that names one call in the correlation metadata.
///
/// Which side mints it depends on who submits the MCP request.
/// When JP submits it, the key is a random value only JP knows, so nothing a
/// caller supplies can name someone else's call.
/// When an agent submits it, the agent chose the identifier before JP saw the
/// call, so the key is that identifier and the guarantee is weaker: an agent
/// that reuses one collides with itself.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct HostCallKey(String);

impl HostCallKey {
    /// A key for a call JP submits.
    fn generate() -> Self {
        Self(format!("{:032x}", random::<u128>()))
    }

    /// The key for a call an agent submits, which is its own tool-call id.
    fn agent(tool_call_id: &str) -> Self {
        Self(tool_call_id.to_owned())
    }

    /// The key for a call under `execution`, given the tool-call id.
    fn for_execution(execution: ToolExecution, tool_call_id: &str) -> Self {
        match execution {
            ToolExecution::Caller => Self::generate(),
            ToolExecution::Agent { .. } => Self::agent(tool_call_id),
        }
    }
}

/// Who submits the MCP request for each call, and a way to wake the router when
/// a route appears.
///
/// The two travel together because they are always used together: a call
/// registers under whichever contract is current, and the router has to
/// reconsider anything it could not place when that happens.
#[derive(Default)]
struct Dispatch {
    mode: SyncMutex<ToolExecution>,
    registered: Notify,
}

impl Dispatch {
    fn mode(&self) -> ToolExecution {
        *locked(&self.mode)
    }

    /// The metadata field carrying the call identifier under the current
    /// contract.
    fn correlation_field(&self) -> &'static str {
        match self.mode() {
            ToolExecution::Caller => CORRELATION_KEY,
            ToolExecution::Agent { correlation_key } => correlation_key,
        }
    }
}

/// Everything the Host keeps for one logical tool call.
struct CallSlot {
    /// The correlation key the service echoes back on every interaction.
    key: HostCallKey,

    /// The call as the assistant requested it.
    /// Argument edits do not change it.
    ///
    /// For an operation of a fanned-out call this is the whole call, envelope
    /// included, which is what the service echoes back on every interaction.
    request: ToolCallRequest,

    /// Which operation of a fanned-out call this slot runs, or `None` for an
    /// ordinary call and for the fanned-out call itself.
    op: Option<usize>,

    /// For an operation, the slot of the call it belongs to, which owns the MCP
    /// request.
    parent: Option<Arc<CallSlot>>,

    /// For a fanned-out call, whether its MCP request has been submitted.
    ///
    /// Every operation's first `prepare` asks for it; only the first submits.
    submitted: AtomicBool,

    /// For a fanned-out call JP submitted, cancelled once its MCP request
    /// returns, so an operation still waiting for its first interaction stops
    /// waiting.
    done: CancellationToken,

    /// For an operation, how it ended, once it has.
    ///
    /// A settled operation is never prepared again: a restart re-prepares only
    /// the operations that were still running.
    settled: SyncMutex<Option<ToolCallResponse>>,

    /// Where the router forwards this call's interactions.
    sender: mpsc::Sender<HostRequest>,

    /// The service's own name for this call, learned from its first
    /// interaction.
    ///
    /// Set once and kept for the life of the call, including across a restart:
    /// pausing and resuming an invocation needs the name the service already
    /// knows it by.
    invocation: SyncMutex<Option<InvocationId>>,

    /// Whether this call is between a paused attempt and its replacement.
    ///
    /// Set by [`Executor::pause_for_restart`] and cleared by the `prepare` that
    /// follows, so that `prepare` reuses the invocation instead of rejecting a
    /// second submission, and the cancellation that ends the paused attempt
    /// does not tear the service-side call down.
    restarting: AtomicBool,

    /// Whether this call's attempt was stopped so the Host can answer it with
    /// the response it records instead.
    ///
    /// Set by [`Executor::hold_for_response`] and cleared by the
    /// acknowledgement that delivers that response.
    /// While set, the cancellation that ends the attempt leaves the
    /// service-side call open.
    held: AtomicBool,

    /// Where to show this tool's stderr, for the length of one attempt.
    ///
    /// Set when an attempt starts and cleared when it ends, so a display that
    /// has moved on is never written to by whatever runs next under this
    /// invocation.
    /// `None` whenever no attempt is in flight, or when nothing is watching
    /// this one.
    stderr: SyncMutex<Option<StderrSink>>,

    /// The call's protocol phase and the Host reply it is parked on.
    ///
    /// Held for the whole of every operation that advances the call, including
    /// across the await on the service, so two operations on one call are
    /// serialised rather than interleaved.
    /// Ordering is not left to that serialisation: [`Phase`] is what makes an
    /// operation arriving out of turn an [`ExecutorError::OutOfOrder`] instead
    /// of a silently wrong reply.
    ///
    /// The cost is that acknowledging a call while it is still executing waits
    /// for the execution attempt to finish.
    /// The coordinator never does that, because it acknowledges only after the
    /// conversation has the response.
    state: Mutex<PendingCall>,
}

/// Where a call's interactions go.
#[derive(Clone)]
enum Route {
    /// An ordinary call: one slot takes everything.
    Call(Arc<CallSlot>),

    /// A fanned-out call: each operation's interactions go to its own slot, and
    /// the call's own `Record` to the call's slot.
    FanOut {
        call: Arc<CallSlot>,
        operations: Vec<Arc<CallSlot>>,
    },
}

impl Route {
    /// The slot of the call itself.
    fn call(&self) -> &Arc<CallSlot> {
        match self {
            Self::Call(slot) | Self::FanOut { call: slot, .. } => slot,
        }
    }
}

/// The calls a turn has in flight, under the two names they are looked up by.
///
/// The router resolves an interaction by the correlation key it carries, and
/// acknowledgement resolves a recorded response by the tool call id the
/// conversation stores.
/// An operation of a fanned-out call is also kept under its call's id and its
/// position, for a restart to find it again.
#[derive(Default)]
struct Registry {
    by_key: HashMap<HostCallKey, Route>,
    by_id: HashMap<(String, Option<usize>), Arc<CallSlot>>,
}

impl Registry {
    fn insert(&mut self, route: Route) {
        let call = route.call().clone();
        self.by_id
            .insert((call.request.id.clone(), None), call.clone());
        if let Route::FanOut { operations, .. } = &route {
            for slot in operations {
                self.by_id
                    .insert((slot.request.id.clone(), slot.op), slot.clone());
            }
        }
        self.by_key.insert(call.key.clone(), route);
    }

    /// Claim a call for acknowledgement, leaving its route in place.
    ///
    /// The service still has barriers to raise before the call finishes, and a
    /// request it cannot route fails closed, so the route outlives the claim.
    fn claim(&mut self, id: &str) -> Option<Arc<CallSlot>> {
        self.by_id.remove(&(id.to_owned(), None))
    }

    /// The slot `id` and `op` name, if it is waiting to be restarted.
    fn restarting(&self, id: &str, op: Option<usize>) -> Option<Arc<CallSlot>> {
        self.by_id
            .get(&(id.to_owned(), op))
            .filter(|slot| slot.restarting.load(Ordering::Acquire))
            .cloned()
    }

    /// The route of the fanned-out call `id`, if it is still in flight.
    fn fan_out(&self, id: &str) -> Option<Route> {
        let call = self.by_id.get(&(id.to_owned(), None))?;
        self.by_key
            .get(&call.key)
            .filter(|route| matches!(route, Route::FanOut { .. }))
            .cloned()
    }

    /// Drop a finished call's route, and its operations with it.
    fn forget(&mut self, slot: &CallSlot) {
        if let Some(Route::FanOut { operations, .. }) = self.by_key.remove(&slot.key) {
            for operation in operations {
                self.by_id
                    .remove(&(operation.request.id.clone(), operation.op));
            }
        }
    }
}

/// Creates MCP-backed executors; configuration and execution context are fixed
/// by the MCP Host when starting the endpoint.
pub(crate) struct TerminalExecutorSource {
    peer: Peer<RoleClient>,
    service: Arc<Service>,
    definitions: IndexMap<String, ToolDefinition>,
    calls: Arc<SyncMutex<Registry>>,

    /// Where an agent submits its own tool requests.
    endpoint: Url,

    /// Who submits each call, and the router's wake-up for new routes.
    dispatch: Arc<Dispatch>,
}

/// Keeps the listener, MCP connection, and Host routing task alive for a turn.
pub(crate) struct ExecutionOwner {
    pub(super) endpoint: Option<Endpoint>,

    /// The Host's own connection, closed before the listener stops.
    ///
    /// Reachable from the shutdown test, which retires this one and puts a
    /// connection it can observe in its place.
    pub(super) client: Option<RunningService<RoleClient, ()>>,

    router: JoinHandle<()>,
}

impl ExecutionOwner {
    /// Cancel pending work and wait for listener/connection cleanup.
    ///
    /// The order matters: admission stops first so nothing new is accepted,
    /// then the client closes its MCP session, which is an HTTP request the
    /// listener still has to serve, and only then does the listener go.
    pub(crate) async fn shutdown(mut self) -> Result<(), EndpointError> {
        if let Some(endpoint) = &self.endpoint {
            endpoint.service().stop();
        }
        let client = match self.client.take() {
            Some(client) => client.cancel().await.map(drop),
            None => Ok(()),
        };
        let server = match self.endpoint.take() {
            Some(endpoint) => endpoint.shutdown().await,
            None => Ok(()),
        };
        self.router.abort();
        client?;
        server
    }
}

impl Drop for ExecutionOwner {
    fn drop(&mut self) {
        self.router.abort();
    }
}

impl TerminalExecutorSource {
    /// Start the execution path without provider-supplied description hints.
    #[cfg(test)]
    pub(crate) async fn start(
        builtins: BuiltinExecutors,
        definitions: &[ToolDefinition],
        tools: &ToolsConfig,
        approvals: Arc<ApprovalStore>,
        invocation: InvocationContext,
        upstream: &Client,
        root: Utf8PathBuf,
    ) -> Result<(Self, ExecutionOwner), EndpointError> {
        Self::start_with_metadata(
            builtins,
            definitions,
            tools,
            approvals,
            invocation,
            upstream,
            root,
            Map::new(),
        )
        .await
    }

    /// Start the common MCP execution path and its private Host connection.
    ///
    /// `metadata` is advertised on every tool's MCP description, for a caller
    /// that reads vendor hints there.
    /// It changes no execution policy.
    pub(crate) async fn start_with_metadata(
        builtins: BuiltinExecutors,
        definitions: &[ToolDefinition],
        tools: &ToolsConfig,
        approvals: Arc<ApprovalStore>,
        invocation: InvocationContext,
        upstream: &Client,
        root: Utf8PathBuf,
        metadata: Map<String, Value>,
    ) -> Result<(Self, ExecutionOwner), EndpointError> {
        let configured = definitions
            .iter()
            .filter_map(|definition| {
                let config = tools.get(&definition.name)?;
                let access =
                    compile_tool_policy(config.access(), &root, &approvals).map_err(|error| {
                        AccessPolicyError {
                            tool: definition.name.clone(),
                            source: Arc::new(error),
                        }
                    });
                Some(ConfiguredTool {
                    definition: definition.clone(),
                    config,
                    access,
                    metadata: metadata.clone(),
                })
            })
            .collect();
        let (service, host) =
            Service::new(configured, upstream.clone(), builtins, root, invocation)?;
        let progress = service.subscribe_progress();
        let endpoint = Endpoint::start(service).await?;
        let client = endpoint.connect().await?;
        let calls = Arc::new(SyncMutex::new(Registry::default()));
        let dispatch = Arc::new(Dispatch::default());
        let router = tokio::spawn(route(host, progress, calls.clone(), dispatch.clone()));
        let source = Self {
            peer: client.peer().clone(),
            service: endpoint.service(),
            definitions: definitions
                .iter()
                .map(|definition| (definition.name.clone(), definition.clone()))
                .collect(),
            calls,
            endpoint: endpoint
                .url()
                .parse()
                .expect("the endpoint binds a loopback HTTP URL"),
            dispatch,
        };
        Ok((source, ExecutionOwner {
            endpoint: Some(endpoint),
            client: Some(client),
            router,
        }))
    }
}

/// Deliver the service's interactions and stderr to the calls they belong to.
///
/// Both streams are drained by one task so a display that stops reading cannot
/// delay a required interaction: progress is dropped, interactions are not.
async fn route(
    mut host: mpsc::Receiver<HostRequest>,
    mut progress: broadcast::Receiver<Progress>,
    calls: Arc<SyncMutex<Registry>>,
    dispatch: Arc<Dispatch>,
) {
    // The service names a call by an `InvocationId` the Host only learns from
    // that call's first interaction, so this index is built here rather than at
    // registration. Being task-local it needs no lock, and it is bounded by the
    // turn's tool calls: the task is aborted when the turn's owner shuts down.
    let mut by_invocation: HashMap<InvocationId, Arc<CallSlot>> = HashMap::new();

    // Requests whose call has not registered yet. Only possible when an agent
    // submits: its MCP request and the announcement JP learns the call from
    // travel on independent transports, so either can arrive first.
    let mut deferred: Vec<HostRequest> = Vec::new();
    let mut watching_progress = true;

    loop {
        let arrived = tokio::select! {
            request = host.recv() => match request {
                Some(request) => Some(request),
                None => break,
            },
            // A call registered, so anything held back may now have a route.
            () = dispatch.registered.notified() => None,
            line = progress.recv(), if watching_progress => {
                match line {
                    Ok(line) => {
                        let sink = by_invocation
                            .get(&line.id)
                            .and_then(|slot| locked(&slot.stderr).clone());
                        if let Some(sink) = sink {
                            sink(&line.line);
                        }
                    }
                    // A display that fell behind loses stderr lines. It never
                    // delays the interactions in the other branch, which is the
                    // point of keeping progress on its own channel.
                    Err(ProgressError::Lagged(_)) => {}
                    Err(ProgressError::Closed) => watching_progress = false,
                }
                continue;
            }
        };

        let mut queued = mem::take(&mut deferred);
        queued.extend(arrived);
        for request in queued {
            let Some(slot) = resolve(&calls, &dispatch, &request) else {
                if dispatch.mode() != ToolExecution::Caller && deferred.len() < DEFERRED_LIMIT {
                    deferred.push(request);
                    continue;
                }
                // The reply sender drops with the request, so the service
                // sees the Host decline and fails the call closed.
                warn!(
                    tool = %request.call.request.name,
                    invocation = ?request.call.id,
                    "No Host route for this MCP invocation; failing it closed."
                );
                continue;
            };
            by_invocation.insert(request.call.id, slot.clone());
            drop(slot.sender.send(request).await);
        }
    }
}

/// Find the call an interaction belongs to, if it names one.
///
/// The correlation key is what identifies the call, and which metadata field
/// carries it depends on who submitted the request: JP's own field when JP
/// submits, the agent's when it does.
/// The service echoes whichever arrived back untouched, so an interaction
/// without a key naming a registered call gets no route.
///
/// The name and arguments are checked afterwards as a consistency assertion,
/// not as a second authority: anything able to supply the key could supply
/// these too.
/// They catch the service echoing the wrong correlation map, which would
/// otherwise show up as a tool that silently never finishes.
///
/// An operation of a fanned-out call goes to its own slot.
/// The Host sized its operations with the same split the service used, and a
/// call the two split differently is refused rather than half-routed.
fn resolve(
    calls: &SyncMutex<Registry>,
    dispatch: &Dispatch,
    request: &HostRequest,
) -> Option<Arc<CallSlot>> {
    let key = request
        .call
        .request
        .correlation
        .get(dispatch.correlation_field())
        .and_then(Value::as_str)
        .map(|value| HostCallKey(value.to_owned()))?;
    let route = locked(calls).by_key.get(&key).cloned()?;
    let slot = match (&route, request.call.operation) {
        (Route::Call(slot) | Route::FanOut { call: slot, .. }, None) => slot.clone(),
        (Route::FanOut { operations, .. }, Some(operation))
            if operation.count == operations.len() =>
        {
            operations.get(operation.index)?.clone()
        }
        _ => {
            warn!(
                tool_call_id = %route.call().request.id,
                operation = ?request.call.operation,
                "The service split this call into operations differently than the Host; \
                 refusing the route."
            );
            return None;
        }
    };
    if slot.request.name != request.call.request.name
        || slot.request.arguments != request.call.request.arguments
    {
        warn!(
            tool_call_id = %slot.request.id,
            expected = %slot.request.name,
            received = %request.call.request.name,
            "Correlation key names a call whose request does not match; refusing the route."
        );
        return None;
    }
    let mut invocation = locked(&slot.invocation);
    match *invocation {
        Some(id) if id != request.call.id => {
            warn!(
                tool_call_id = %slot.request.id,
                bound = ?id,
                received = ?request.call.id,
                "Correlation key is already bound to another invocation; refusing the route."
            );
            return None;
        }
        Some(_) => {}
        None => {
            debug!(
                invocation = ?request.call.id,
                tool_call_id = %slot.request.id,
                tool = %slot.request.name,
                "Associated MCP invocation with Host tool call"
            );
            *invocation = Some(request.call.id);
        }
    }
    drop(invocation);
    Some(slot)
}

impl ExecutorSource for TerminalExecutorSource {
    fn endpoint(&self) -> Option<Url> {
        Some(self.endpoint.clone())
    }

    fn set_execution(&self, execution: ToolExecution) -> Result<(), ExecutorError> {
        *locked(&self.dispatch.mode) = execution;
        // A held-back request may be routable under the new contract.
        self.dispatch.registered.notify_one();
        Ok(())
    }

    fn create(
        &self,
        request: ToolCallRequest,
        config: ToolConfigWithDefaults,
    ) -> Option<CallExecutors> {
        let definition = self.definitions.get(&request.name)?;

        // Sized with the split the service applies to the same call, so every
        // operation it runs has an executor waiting for it.
        let operations = match config.fan_out() {
            None => None,
            Some(_) => match fan_out::split(definition, &request.arguments) {
                Split::Envelope(operations) => Some(operations),
                Split::Bare | Split::Malformed(_) => None,
            },
        };
        Some(match operations {
            None => CallExecutors::call(self.call_executor(request, config)),
            Some(operations) => self.fan_out_executors(&request, &config, operations),
        })
    }

    fn acknowledge(&self, review: Review) -> BoxFuture<'_, Result<(), ExecutorError>> {
        Box::pin(async move {
            // Claiming makes a second acknowledgement a no-op. Forgetting the
            // call afterwards is what bounds the registry; a turn that ends
            // without acknowledging every call drops the whole source.
            let Some(slot) = locked(&self.calls).claim(&review.response.id) else {
                return Ok(());
            };
            let result = slot.acknowledge(&review).await;
            locked(&self.calls).forget(&slot);
            result
        })
    }

    fn settle(&self, review: Review, op: usize) -> BoxFuture<'_, Result<(), ExecutorError>> {
        Box::pin(async move {
            let slot = locked(&self.calls)
                .by_id
                .get(&(review.response.id.clone(), Some(op)))
                .cloned();
            match slot {
                Some(slot) => slot.settle(&review).await,
                None => Ok(()),
            }
        })
    }
}

impl TerminalExecutorSource {
    /// The tool definitions callers are shown, in configured order.
    ///
    /// A tool with `fan_out` configured appears with its envelope schema, so
    /// this, not the resolved definitions, is what a provider request carries.
    pub(crate) fn advertised(&self) -> Vec<ToolDefinition> {
        self.service.definitions().cloned().collect()
    }

    /// The executor for an ordinary call.
    fn call_executor(
        &self,
        request: ToolCallRequest,
        config: ToolConfigWithDefaults,
    ) -> Box<dyn Executor> {
        // A restarted call keeps its slot, and with it the service-side
        // invocation the paused attempt belongs to. Building a second slot
        // would strand that invocation and submit a duplicate call.
        // Bound on its own statement so the registry lock is released before
        // `insert` takes it again.
        let restarting = locked(&self.calls).restarting(&request.id, None);
        let slot = restarting.unwrap_or_else(|| {
            let slot = self.slot(request, None, None);
            locked(&self.calls).insert(Route::Call(slot.clone()));
            // An agent's MCP request may already be waiting on this route.
            self.dispatch.registered.notify_one();
            slot
        });
        self.executor(slot.request.arguments.clone(), config, slot)
    }

    /// The executors for a fanned-out call, one per operation.
    fn fan_out_executors(
        &self,
        request: &ToolCallRequest,
        config: &ToolConfigWithDefaults,
        operations: Vec<Map<String, Value>>,
    ) -> CallExecutors {
        // A restart re-prepares the same call, whose operations keep their
        // slots: a settled one answers from what it settled with, and one that
        // was paused resumes its invocation.
        // Bound on its own statement so the registry lock is released before
        // `insert` takes it again.
        let existing = locked(&self.calls).fan_out(&request.id);
        let (call, slots) = match existing {
            Some(Route::FanOut {
                call,
                operations: slots,
            }) if slots.len() == operations.len() => (call, slots),
            _ => {
                let call = self.slot(request.clone(), None, None);
                let slots = (0..operations.len())
                    .map(|index| self.slot(request.clone(), Some(index), Some(call.clone())))
                    .collect::<Vec<_>>();
                locked(&self.calls).insert(Route::FanOut {
                    call: call.clone(),
                    operations: slots.clone(),
                });
                self.dispatch.registered.notify_one();
                (call, slots)
            }
        };
        CallExecutors {
            operations: slots
                .into_iter()
                .zip(operations)
                .map(|(slot, arguments)| self.executor(arguments, config.clone(), slot))
                .collect(),
            fan_out: Some(Arc::new(FanOutHandle { slot: call })),
        }
    }

    fn slot(
        &self,
        request: ToolCallRequest,
        op: Option<usize>,
        parent: Option<Arc<CallSlot>>,
    ) -> Arc<CallSlot> {
        let execution = self.dispatch.mode();
        let (sender, receiver) = mpsc::channel(8);
        let parent_done = parent.as_ref().map(|parent| parent.done.clone());
        Arc::new(CallSlot {
            key: HostCallKey::for_execution(execution, &request.id),
            request,
            op,
            parent,
            submitted: AtomicBool::new(false),
            done: CancellationToken::new(),
            settled: SyncMutex::new(None),
            sender,
            invocation: SyncMutex::new(None),
            restarting: AtomicBool::new(false),
            held: AtomicBool::new(false),
            stderr: SyncMutex::new(None),
            state: Mutex::new(PendingCall {
                receiver,
                task: None,
                phase: Phase::Idle,
                execution,
                service: self.service.clone(),
                invocation: None,
                parent_done,
            }),
        })
    }

    fn executor(
        &self,
        arguments: Map<String, Value>,
        config: ToolConfigWithDefaults,
        slot: Arc<CallSlot>,
    ) -> Box<dyn Executor> {
        Box::new(ToolExecutor {
            arguments,
            config,
            peer: self.peer.clone(),
            service: self.service.clone(),
            slot,
            formatted: None,
        })
    }
}

/// The Host's handle on a fanned-out call as a whole.
struct FanOutHandle {
    slot: Arc<CallSlot>,
}

#[async_trait]
impl FanOutCall for FanOutHandle {
    async fn recorded(&self) -> Result<ToolCallResponse, ExecutorError> {
        let mut state = self.slot.state.lock().await;
        match state.next().await? {
            Received::Interaction(interaction) => match *interaction {
                Interaction::Record { recording, reply } => {
                    state.phase = Phase::Record(reply);
                    Ok(response(&self.slot.request.id, &recording.result))
                }
                _ => Err(ExecutorError::UnexpectedInteraction { phase: "folding" }),
            },
            // Returned without asking to be recorded, which the service does
            // only for a call it could not start.
            Received::Finished(result) => Ok(response(&self.slot.request.id, &result)),
        }
    }
}

impl CallSlot {
    /// Submit the fanned-out call's MCP request, once for all its operations.
    ///
    /// Nothing to do when an agent submits its own calls.
    async fn submit(&self, peer: &Peer<RoleClient>) {
        if self.submitted.swap(true, Ordering::AcqRel) {
            return;
        }
        let mut state = self.state.lock().await;
        if state.execution != ToolExecution::Caller {
            return;
        }
        let mut params = CallToolRequestParams::new(self.request.name.clone());
        params.arguments = Some(self.request.arguments.clone());
        params.meta = Some(Meta(Map::from_iter([(
            CORRELATION_KEY.into(),
            self.key.0.clone().into(),
        )])));
        let peer = peer.clone();
        let done = self.done.clone();
        state.task = Some(tokio::spawn(async move {
            let result = peer.call_tool(params).await;
            done.cancel();
            result
        }));
    }

    /// Take an operation's settlement: remember how it ended and let the
    /// service move on.
    fn take_settlement(
        &self,
        state: &mut PendingCall,
        settlement: &Recording,
        reply: Reply<()>,
    ) -> ToolCallResponse {
        let settled = response(&self.request.id, &settlement.result);
        *locked(&self.settled) = Some(settled.clone());
        state.phase = Phase::Finished;
        drop(reply.send(Ok(())));
        settled
    }

    /// Resolve an operation of a fanned-out call with what the Host settled on,
    /// without waiting for the call to be recorded.
    ///
    /// Its call is recorded once every operation is resolved, so an operation
    /// cannot wait for that the way an ordinary call waits for acknowledgement.
    async fn settle(&self, review: &Review) -> Result<(), ExecutorError> {
        let mut state = self.state.lock().await;
        if locked(&self.settled).is_some() {
            return Ok(());
        }
        if self.held.swap(false, Ordering::AcqRel) {
            // The attempt already stopped; the Host's result stands in for it,
            // and no settlement follows.
            state.phase = Phase::Finished;
            *locked(&self.settled) = Some(review.response.clone());
            // `false` means the operation finished on its own first, which
            // its settlement then reports.
            if let Some(id) = *locked(&self.invocation) {
                let _ = state.service.complete_call(id, approved(None, review));
            }
            return Ok(());
        }
        match mem::replace(&mut state.phase, Phase::Finished) {
            // Nothing outstanding: a failed attempt already ended the
            // operation.
            Phase::Idle | Phase::Finished | Phase::Record(_) => return Ok(()),
            Phase::Admission(reply) => drop(reply.send(Ok(Admission::Complete {
                result: approved(None, review),
            }))),
            Phase::Release(reply) => drop(reply.send(Ok(ReleaseDecision::Complete {
                result: approved(None, review),
            }))),
            Phase::Input { reply, .. } => drop(reply.send(Ok(InputAnswer::Complete {
                result: approved(None, review),
            }))),
            Phase::Review { offered, reply } => {
                drop(reply.send(Ok(approved(Some(offered), review))));
            }
        }
        loop {
            match state.next().await? {
                Received::Interaction(interaction) => match *interaction {
                    Interaction::Review { result, reply, .. } => {
                        drop(reply.send(Ok(approved(Some(result), review))));
                    }
                    Interaction::Settled { settlement, reply } => {
                        self.take_settlement(&mut state, &settlement, reply);
                        return Ok(());
                    }
                    _ => {
                        return Err(ExecutorError::UnexpectedInteraction { phase: "settling" });
                    }
                },
                Received::Finished(_) => return Ok(()),
            }
        }
    }
}

/// The Host reply a call is currently parked on.
///
/// Exactly one is outstanding at a time: the service asks for the next thing
/// only once the previous reply reaches it.
enum Phase {
    /// Created, but the MCP call has not been submitted.
    Idle,

    /// Submitted; the Host owes an admission decision.
    Admission(Reply<Admission>),

    /// Admitted; the Host owes execution release.
    Release(Reply<ReleaseDecision>),

    /// A tool asked for input; the Host owes an answer.
    Input {
        id: QuestionId,
        reply: Reply<InputAnswer>,
    },

    /// A result is waiting for the Host to approve or replace its content.
    ///
    /// `offered` is what the service produced.
    /// A Host that does not edit gets this value back, so resources,
    /// annotations, structured content, and error details survive a review that
    /// changed nothing.
    Review {
        offered: ToolResult,
        reply: Reply<ToolResult>,
    },

    /// Content is waiting for the Host to confirm it recorded it.
    Record(Reply<()>),

    /// The MCP call returned; nothing is outstanding.
    Finished,
}

impl Phase {
    /// How this phase reads in a protocol diagnostic.
    fn name(&self) -> &'static str {
        match self {
            Self::Idle => "not yet submitted",
            Self::Admission(_) => "awaiting admission",
            Self::Release(_) => "awaiting release",
            Self::Input { .. } => "awaiting input",
            Self::Review { .. } => "awaiting result review",
            Self::Record(_) => "awaiting recording",
            Self::Finished => "finished",
        }
    }
}

struct PendingCall {
    receiver: mpsc::Receiver<HostRequest>,

    /// The MCP request JP submitted, when JP is the one submitting.
    /// `None` for a call an agent submits: the request is already in flight
    /// somewhere JP cannot await.
    task: Option<JoinHandle<Result<jp_mcp::CallToolResult, McpCallError>>>,

    phase: Phase,

    /// Who submits this call's MCP request, fixed when the call was created.
    execution: ToolExecution,

    /// Reached to observe cancellation of an agent-submitted call, which has no
    /// task to select on.
    service: Arc<Service>,

    /// The service's name for this call, once an interaction has carried it.
    invocation: Option<InvocationId>,

    /// For an operation of a fanned-out call, cancelled once the call's MCP
    /// request returns.
    ///
    /// An operation holds no request of its own to wait on, so this is what
    /// ends a wait for an operation the service will never start.
    parent_done: Option<CancellationToken>,
}

impl PendingCall {
    /// Whether somebody other than JP holds this call's MCP request, and so
    /// receives its response.
    fn submitted_elsewhere(&self) -> bool {
        matches!(self.execution, ToolExecution::Agent { .. })
    }

    /// Whether this is an operation of a fanned-out call.
    fn is_operation(&self) -> bool {
        self.parent_done.is_some()
    }
}

enum Received {
    /// Boxed because a call holds one of these only while dispatching it, and
    /// the largest variant is several times the size of the rest.
    Interaction(Box<Interaction>),

    /// The MCP call returned its final result.
    Finished(ToolResult),
}

impl PendingCall {
    /// Wait for the next Host interaction the service still cares about, or for
    /// the MCP call to return.
    ///
    /// An interaction the service has abandoned is skipped rather than
    /// answered: after a restart its reply channel is already closed, and
    /// replying would report a protocol error for a barrier nobody is waiting
    /// on.
    async fn next(&mut self) -> Result<Received, ExecutorError> {
        loop {
            let received = self.receive().await?;
            if matches!(&received, Received::Interaction(interaction) if interaction.is_expired()) {
                continue;
            }
            return Ok(received);
        }
    }

    /// Take the next thing to happen to this call, whoever submitted it.
    async fn receive(&mut self) -> Result<Received, ExecutorError> {
        // An operation's MCP request belongs to its call, so an operation
        // waits the way a call an agent submitted does: on its interactions
        // alone.
        if self.is_operation() || matches!(self.execution, ToolExecution::Agent { .. }) {
            return self.receive_agent().await;
        }
        let task = self.task.as_mut().ok_or(ExecutorError::HostDisconnected)?;
        tokio::select! {
            request = self.receiver.recv() => {
                let request = request.ok_or(ExecutorError::HostDisconnected)?;
                self.invocation = Some(request.call.id);
                Ok(Received::Interaction(Box::new(request.interaction)))
            }
            result = task => {
                self.task = None;
                self.phase = Phase::Finished;
                let result = result?.map_err(|error| ExecutorError::Transport(Box::new(error)))?;
                Ok(Received::Finished(
                    from_mcp(result).map_err(ExecutorError::MalformedResult)?,
                ))
            }
        }
    }

    /// Wait on an agent-submitted call, which JP holds no request future for.
    ///
    /// Before the first interaction the call has no service-side name, so the
    /// only thing bounding the wait is the clock: the agent may never submit
    /// what it announced.
    /// Afterwards the service's own cancellation token stands in for the task a
    /// Host-submitted call would have been selecting on.
    async fn receive_agent(&mut self) -> Result<Received, ExecutorError> {
        let request = match self.invocation {
            Some(id) => match self.service.call_cancellation(id) {
                Some(token) => tokio::select! {
                    biased;
                    () = token.cancelled() => Err(ExecutorError::Cancelled),
                    request = self.receiver.recv() => {
                        request.ok_or(ExecutorError::HostDisconnected)
                    }
                },
                // The invocation has left the active set, so nothing further
                // is coming for it.
                None => Err(ExecutorError::Cancelled),
            },
            None => self.first_request().await,
        };

        let request = match request {
            Ok(request) => request,
            Err(error) => {
                self.phase = Phase::Finished;
                return Err(error);
            }
        };
        self.invocation = Some(request.call.id);
        Ok(Received::Interaction(Box::new(request.interaction)))
    }

    /// Wait for the first interaction of a call JP holds no request future for.
    ///
    /// For an operation of a fanned-out call, the call's MCP request returning
    /// also ends the wait: the service will start no operation after that.
    async fn first_request(&mut self) -> Result<HostRequest, ExecutorError> {
        let parent_done = self.parent_done.clone().unwrap_or_default();
        tokio::select! {
            received = timeout(AGENT_CALL_TIMEOUT, self.receiver.recv()) => match received {
                Ok(request) => request.ok_or(ExecutorError::HostDisconnected),
                Err(_) => Err(ExecutorError::ExternalCallTimeout),
            },
            () = parent_done.cancelled(), if self.parent_done.is_some() => {
                Err(ExecutorError::HostDisconnected)
            }
        }
    }
}

/// The result the service should deliver, given what the Host recorded.
///
/// An unedited review returns the result the service offered, so resources,
/// annotations, structured content, and error details survive a review that
/// changed nothing.
/// Anything else is rebuilt from the recorded text, which is all the Host's
/// replacement content amounts to.
fn approved(offered: Option<ToolResult>, review: &Review) -> ToolResult {
    match offered {
        Some(offered) if !review.edited => offered,
        _ => ToolResult::from(review.response.result.clone()),
    }
}

impl CallSlot {
    /// Release whichever barrier the call is parked on with the Host's final
    /// content, then drain the call to its MCP response.
    async fn acknowledge(&self, review: &Review) -> Result<(), ExecutorError> {
        let mut state = self.state.lock().await;
        if self.held.swap(false, Ordering::AcqRel) {
            return self.deliver_held(&mut state, review).await;
        }
        let recorded = matches!(state.phase, Phase::Record(_));
        match mem::replace(&mut state.phase, Phase::Finished) {
            // Nothing is outstanding: the call already delivered its result, or
            // never started because preparation failed.
            Phase::Idle | Phase::Finished => return Ok(()),
            Phase::Admission(reply) => drop(reply.send(Ok(Admission::Complete {
                result: approved(None, review),
            }))),
            Phase::Release(reply) => drop(reply.send(Ok(ReleaseDecision::Complete {
                result: approved(None, review),
            }))),
            Phase::Input { reply, .. } => drop(reply.send(Ok(InputAnswer::Complete {
                result: approved(None, review),
            }))),
            Phase::Review { offered, reply } => {
                drop(reply.send(Ok(approved(Some(offered), review))));
            }
            Phase::Record(reply) => drop(reply.send(Ok(()))),
        }
        if recorded && state.submitted_elsewhere() {
            return Ok(());
        }
        self.drain(&mut state, review).await
    }

    /// Hand a held call the content the Host recorded for it.
    ///
    /// The attempt already stopped, so no barrier is outstanding: the service
    /// delivers this content as the call's MCP response.
    async fn deliver_held(
        &self,
        state: &mut PendingCall,
        review: &Review,
    ) -> Result<(), ExecutorError> {
        state.phase = Phase::Finished;
        let Some(id) = *locked(&self.invocation) else {
            return Ok(());
        };
        // `false` means the call finished on its own first; its caller already
        // has that result.
        if !state.service.complete_call(id, approved(None, review)) {
            return Ok(());
        }
        if state.submitted_elsewhere() {
            return Ok(());
        }
        self.drain(state, review).await
    }

    /// Answer the service's remaining barriers and check what it delivered.
    ///
    /// A call JP submitted ends at its MCP response, which is checked against
    /// what the Host recorded.
    /// A call an agent submitted has no response to wait for here — it goes to
    /// the agent — so recording is the last barrier and the drain ends there.
    async fn drain(&self, state: &mut PendingCall, review: &Review) -> Result<(), ExecutorError> {
        loop {
            match state.next().await? {
                Received::Interaction(interaction) => match *interaction {
                    // The Host settled this call at an earlier barrier, so the
                    // content it recorded is also what it approves here.
                    Interaction::Review { result, reply, .. } => {
                        drop(reply.send(Ok(approved(Some(result), review))));
                    }
                    Interaction::Record { reply, .. } => {
                        drop(reply.send(Ok(())));
                        if state.submitted_elsewhere() {
                            state.phase = Phase::Finished;
                            return Ok(());
                        }
                    }
                    _ => {
                        return Err(ExecutorError::UnexpectedInteraction { phase: "recording" });
                    }
                },
                Received::Finished(delivered) => {
                    let delivered = response(&review.response.id, &delivered);
                    return if delivered.result == review.response.result {
                        Ok(())
                    } else {
                        Err(ExecutorError::DeliveryMismatch)
                    };
                }
            }
        }
    }
}

/// Represents one logical MCP call, including its pending Host interactions.
pub(crate) struct ToolExecutor {
    /// The arguments to execute with, which Host editing may replace.
    arguments: Map<String, Value>,
    config: ToolConfigWithDefaults,
    peer: Peer<RoleClient>,
    service: Arc<Service>,
    slot: Arc<CallSlot>,
    formatted: Option<Formatted>,
}

impl ToolExecutor {
    /// Cancel the service-side invocation, if the service has named it yet.
    fn cancel_invocation(&self) {
        if let Some(id) = *locked(&self.slot.invocation) {
            self.service.cancel_call(id);
        }
    }

    /// Report an execution attempt that ended in `error`.
    ///
    /// `released` is whether the service had been told to run the tool when the
    /// attempt failed, which decides whether the tool may have run.
    fn settle_failure(
        &self,
        state: &mut PendingCall,
        error: ExecutorError,
        released: bool,
    ) -> ExecutorResult {
        // A paused call is meant to come back, and a held one waits for the
        // Host's response, so either way its invocation stays alive and the
        // cancellation that ended this attempt is reported without tearing the
        // service-side call down.
        if self.slot.restarting.load(Ordering::Acquire) || self.slot.held.load(Ordering::Acquire) {
            return ExecutorResult::Completed(ToolCallResponse {
                id: self.slot.request.id.clone(),
                result: Err(error.to_string()),
            });
        }
        // Anything else cannot continue, so stop the service-side work rather
        // than leaving it parked on a reply that never arrives.
        self.cancel_invocation();
        state.phase = Phase::Finished;
        if error.is_call_outcome() {
            return ExecutorResult::Completed(ToolCallResponse {
                id: self.slot.request.id.clone(),
                result: Err(error.to_string()),
            });
        }
        if released {
            return ExecutorResult::OutcomeUnknown(error);
        }
        ExecutorResult::Failed(error)
    }
}

#[async_trait]
impl Executor for ToolExecutor {
    fn tool_id(&self) -> &str {
        &self.slot.request.id
    }

    fn tool_name(&self) -> &str {
        &self.slot.request.name
    }

    fn op_index(&self) -> Option<usize> {
        self.slot.op
    }

    fn arguments(&self) -> &Map<String, Value> {
        &self.arguments
    }

    fn formatted_arguments(&self) -> Option<&Formatted> {
        self.formatted.as_ref()
    }

    fn needs_permission(&self) -> bool {
        !matches!(self.config.run(), RunMode::Unattended | RunMode::Skip)
    }

    fn permission_info(&self) -> Option<PermissionInfo> {
        let run_mode = self.config.run();
        if matches!(run_mode, RunMode::Unattended | RunMode::Skip) {
            return None;
        }
        Some(PermissionInfo {
            tool_id: self.slot.request.id.clone(),
            state_key: self.state_key(),
            tool_name: self.slot.request.name.clone(),
            tool_source: self.config.source().clone(),
            run_mode,
            arguments: self.arguments.clone().into(),
        })
    }

    fn set_arguments(&mut self, args: Value) {
        if let Value::Object(arguments) = args {
            self.arguments = arguments;
        }
    }

    fn pause_for_restart(&self) -> bool {
        let Some(id) = *locked(&self.slot.invocation) else {
            // Nothing to pause: the service has not named this call yet, so a
            // restart has to submit it afresh.
            return false;
        };
        // Set before asking, so the cancellation that follows sees a paused
        // call rather than one to tear down.
        self.slot.restarting.store(true, Ordering::Release);
        if self.service.pause_call(id) {
            return true;
        }
        self.slot.restarting.store(false, Ordering::Release);
        false
    }

    fn hold_for_response(&self) -> bool {
        let Some(id) = *locked(&self.slot.invocation) else {
            return false;
        };
        // Set before pausing, so the cancellation that follows sees a held
        // call rather than one to tear down.
        self.slot.held.store(true, Ordering::Release);
        if self.service.pause_call(id) {
            return true;
        }
        self.slot.held.store(false, Ordering::Release);
        false
    }

    async fn prepare(
        &mut self,
        render_arguments: bool,
    ) -> Result<Option<ToolCallResponse>, ExecutorError> {
        let mut state = self.slot.state.lock().await;

        // An operation that settled before a restart keeps its result.
        if let Some(settled) = locked(&self.slot.settled).clone() {
            return Ok(Some(settled));
        }

        let restarting = self.slot.restarting.swap(false, Ordering::AcqRel);

        if restarting {
            // The paused attempt left the call parked on a barrier the service
            // has since abandoned. Drop it and ask the service for a fresh
            // preparation cycle on the same invocation.
            state.phase = Phase::Idle;
            let id = state.invocation.ok_or(ExecutorError::OutOfOrder {
                operation: "be restarted",
                phase: "not yet submitted",
            })?;
            self.service.resume_call(id);
        } else if !matches!(state.phase, Phase::Idle) {
            return Err(ExecutorError::OutOfOrder {
                operation: "be submitted",
                phase: state.phase.name(),
            });
        }

        // A restart reuses the request already in flight, and an agent submits
        // its own; only a first Host-submitted call issues one here. An
        // operation's request is its call's, submitted once for all of them.
        if !restarting && let Some(parent) = &self.slot.parent {
            parent.submit(&self.peer).await;
        } else if !restarting && state.execution == ToolExecution::Caller {
            let mut params = CallToolRequestParams::new(self.slot.request.name.clone());
            params.arguments = Some(self.arguments.clone());
            params.meta = Some(Meta(Map::from_iter([(
                CORRELATION_KEY.into(),
                self.slot.key.0.clone().into(),
            )])));
            let peer = self.peer.clone();
            state.task = Some(tokio::spawn(async move { peer.call_tool(params).await }));
        }
        loop {
            match state.next().await? {
                Received::Interaction(interaction) => match *interaction {
                    Interaction::RenderArguments { reply } => {
                        drop(reply.send(Ok(render_arguments)));
                    }
                    Interaction::Prepare {
                        arguments,
                        formatted_arguments,
                        reply,
                        ..
                    } => {
                        self.arguments = arguments;
                        self.formatted = formatted_arguments;
                        state.phase = Phase::Admission(reply);
                        // Remember the service's name for this call while a
                        // reply is in hand: a later restart has to resume this
                        // invocation rather than start another.
                        if let Some(id) = state.invocation {
                            *locked(&self.slot.invocation) = Some(id);
                        }
                        return Ok(None);
                    }
                    Interaction::Record { recording, reply } => {
                        let response = response(&self.slot.request.id, &recording.result);
                        state.phase = Phase::Record(reply);
                        return Ok(Some(response));
                    }
                    // Resolved without being prepared: its arguments failed
                    // validation, or the tool is configured not to run.
                    Interaction::Settled { settlement, reply } => {
                        return Ok(Some(self.slot.take_settlement(
                            &mut state,
                            &settlement,
                            reply,
                        )));
                    }
                    _ => {
                        return Err(ExecutorError::UnexpectedInteraction { phase: "preparing" });
                    }
                },
                Received::Finished(result) => {
                    return Ok(Some(response(&self.slot.request.id, &result)));
                }
            }
        }
    }

    async fn approve(&mut self) -> Result<(), ExecutorError> {
        let mut state = self.slot.state.lock().await;
        let Phase::Admission(reply) = mem::replace(&mut state.phase, Phase::Finished) else {
            state.phase = Phase::Finished;
            return Err(ExecutorError::OutOfOrder {
                operation: "be approved",
                phase: "not awaiting admission",
            });
        };
        reply
            .send(Ok(Admission::Run {
                arguments: self.arguments.clone(),
            }))
            .map_err(|_| ExecutorError::ReplyExpired {
                operation: "approval",
            })?;
        match state.next().await? {
            Received::Interaction(interaction) => match *interaction {
                Interaction::Release {
                    arguments,
                    formatted_arguments,
                    reply,
                } => {
                    self.arguments = arguments;
                    self.formatted = formatted_arguments;
                    state.phase = Phase::Release(reply);
                    Ok(())
                }
                // An operation whose approved arguments fail validation
                // settles with the error instead.
                Interaction::Settled { settlement, reply } => {
                    let message = settlement.result.to_text();
                    self.slot.take_settlement(&mut state, &settlement, reply);
                    Err(ExecutorError::Rejected { message })
                }
                _ => Err(ExecutorError::UnexpectedInteraction { phase: "approving" }),
            },
            // Validating the approved arguments can fail the call outright,
            // which arrives as the MCP response rather than another barrier.
            Received::Finished(result) if result.is_error() => Err(ExecutorError::Rejected {
                message: result.to_text(),
            }),
            Received::Finished(_) => {
                Err(ExecutorError::UnexpectedInteraction { phase: "approving" })
            }
        }
    }

    async fn execute(
        &self,
        answers: &IndexMap<String, Value>,
        cancellation: CancellationToken,
        stderr: Option<StderrSink>,
    ) -> ExecutorResult {
        let mut state = self.slot.state.lock().await;
        *locked(&self.slot.stderr) = stderr;
        // Whether the service was told to run the tool. A failure before that
        // point means nothing ran; after it, the tool may have.
        let mut released = false;
        let attempt = async {
            match mem::replace(&mut state.phase, Phase::Finished) {
                Phase::Release(reply) => {
                    reply.send(Ok(ReleaseDecision::Execute)).map_err(|_| {
                        ExecutorError::ReplyExpired {
                            operation: "release",
                        }
                    })?;
                    released = true;
                }
                Phase::Input { id, reply } => {
                    let answer = answers
                        .get(id.as_str())
                        .ok_or(ExecutorError::MissingAnswer)?
                        .clone();
                    reply.send(Ok(InputAnswer::Answer(answer))).map_err(|_| {
                        ExecutorError::ReplyExpired {
                            operation: "inquiry",
                        }
                    })?;
                    released = true;
                }
                phase => {
                    let name = phase.name();
                    state.phase = phase;
                    return Err(ExecutorError::OutOfOrder {
                        operation: "execute",
                        phase: name,
                    });
                }
            }
            let id = &self.slot.request.id;
            match state.next().await? {
                Received::Interaction(interaction) => match *interaction {
                    Interaction::Input {
                        request,
                        supporting,
                        answers,
                        reply,
                    } => {
                        let question = question(request, &supporting);
                        state.phase = Phase::Input {
                            id: question.id.clone(),
                            reply,
                        };
                        Ok(ExecutorResult::NeedsInput {
                            tool_id: id.clone(),
                            tool_name: self.slot.request.name.clone(),
                            source: InquirySource::tool(&self.slot.request.name),
                            question,
                            accumulated_answers: answers,
                        })
                    }
                    Interaction::Review { result, reply, .. } => {
                        let offered = response(id, &result);
                        state.phase = Phase::Review {
                            offered: result,
                            reply,
                        };
                        Ok(ExecutorResult::Completed(offered))
                    }
                    Interaction::Record { recording, reply } => {
                        let response = response(id, &recording.result);
                        state.phase = Phase::Record(reply);
                        Ok(ExecutorResult::Completed(response))
                    }
                    // An operation ends here: it ran, or a `stop` policy ruled
                    // it out after the Host released it.
                    Interaction::Settled { settlement, reply } => Ok(ExecutorResult::Completed(
                        self.slot.take_settlement(&mut state, &settlement, reply),
                    )),
                    _ => Err(ExecutorError::UnexpectedInteraction { phase: "executing" }),
                },
                Received::Finished(result) => Ok(ExecutorResult::Completed(response(id, &result))),
            }
        };
        let result = tokio::select! {
            biased;
            () = cancellation.cancelled() => Err(ExecutorError::Cancelled),
            result = attempt => result,
        };
        // The service reports an outcome only once the attempt's process has
        // exited and its stderr has been drained, so the sink has nothing left
        // to receive. A question's next attempt brings its own.
        *locked(&self.slot.stderr) = None;
        result.unwrap_or_else(|error| self.settle_failure(&mut state, error, released))
    }
}

/// Render a shared input request as the question the terminal prompts with.
///
/// The supporting blocks are the content the tool emitted before its request;
/// the terminal shows them above the prompt.
fn question(request: InputRequest, supporting: &[ContentBlock]) -> Question {
    let preamble = supporting
        .iter()
        .filter_map(ContentBlock::as_text)
        .collect::<Vec<_>>()
        .join("\n\n");
    let mut question = Question::new(request.id, request.label, request.answer_type);
    question.pre_amble = (!preamble.is_empty()).then_some(preamble);
    question.default = request.default;
    question
}

#[cfg(test)]
#[path = "mcp_executor_tests.rs"]
mod tests;
