//! MCP Host adapter for tool calls through JP's loopback HTTP endpoint.
//!
//! [`TerminalExecutorSource`] owns the endpoint, the Host's MCP connection, and
//! the task that routes the service's private interactions back to the tool
//! call that submitted them.
//! Each [`ToolExecutor`] drives one logical call: it holds the single-use Host
//! reply the service is waiting on, and hands the coordinator a [`Delivery`]
//! whenever the call produces something the conversation should record.

use std::{
    collections::HashMap,
    mem,
    sync::{Arc, Mutex as SyncMutex, MutexGuard, PoisonError},
};

use async_trait::async_trait;
use camino::Utf8PathBuf;
use futures::future::BoxFuture;
use indexmap::IndexMap;
use jp_config::conversation::tool::{RunMode, ToolConfigWithDefaults, ToolsConfig};
use jp_conversation::event::{InquirySource, ToolCallRequest, ToolCallResponse};
use jp_mcp::{
    Client,
    server::{
        InvocationContext, StderrSink,
        builtin::BuiltinExecutors,
        http::{Endpoint, EndpointError},
        result::from_mcp,
        service::{
            AccessPolicyError, Admission, ConfiguredTool, Formatted, HostReply, HostRequest,
            InputAnswer, Interaction, InvocationId, Progress, ReleaseDecision, Service,
        },
    },
};
use jp_tool::{ContentBlock, InputRequest, Question, QuestionId, ToolDefinition, ToolResult};
use rand::random;
use rmcp::{
    Peer, ServiceError as McpCallError,
    model::{CallToolRequestParams, Meta},
    service::{RoleClient, RunningService},
};
use serde_json::{Map, Value};
use tokio::{
    sync::{Mutex, broadcast, broadcast::error::RecvError as ProgressError, mpsc, oneshot},
    task::JoinHandle,
};
use tokio_util::sync::CancellationToken;
use tracing::{debug, warn};

use super::executor::{
    Executor, ExecutorError, ExecutorResult, ExecutorSource, PermissionInfo, Review, response,
};
use crate::access::{approvals::ApprovalStore, compile::compile_tool_policy};

/// Where a call's correlation key travels on its MCP request.
///
/// The value is generated by the Host and never derived from anything a caller
/// supplies, so a third-party MCP client cannot name someone else's call.
const CORRELATION_KEY: &str = "computer.jp/hostCall";

type Reply<T> = oneshot::Sender<HostReply<T>>;

fn locked<T>(value: &SyncMutex<T>) -> MutexGuard<'_, T> {
    // No caller code runs under these locks, so recovering a poisoned one lets
    // an unrelated panic elsewhere finish this turn's calls rather than hang
    // them.
    value.lock().unwrap_or_else(PoisonError::into_inner)
}

/// Private correlation value generated by the Host, not a provider tool-call
/// ID.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct HostCallKey(String);

impl HostCallKey {
    fn generate() -> Self {
        Self(format!("{:032x}", random::<u128>()))
    }
}

/// Everything the Host keeps for one logical tool call.
struct CallSlot {
    /// The correlation key the service echoes back on every interaction.
    key: HostCallKey,

    /// The call as the assistant requested it.
    /// Argument edits do not change it.
    request: ToolCallRequest,

    /// Where the router forwards this call's interactions.
    sender: mpsc::Sender<HostRequest>,

    /// The service's own name for this call, learned from its first
    /// interaction.
    invocation: SyncMutex<Option<InvocationId>>,

    /// Where to show this tool's stderr, for the length of one attempt.
    ///
    /// Set when an attempt starts and cleared when it ends, so a display that
    /// has moved on is never written to by whatever runs next under this
    /// invocation.
    /// `None` whenever no attempt is in flight, or when nothing is watching
    /// this one.
    stderr: SyncMutex<Option<StderrSink>>,

    /// The call's protocol phase and the Host reply it is parked on.
    ///
    /// Held for the whole of every operation that advances the call, including
    /// across the await on the service, so two operations on one call are
    /// serialised rather than interleaved.
    /// Ordering is not left to that serialisation: [`Phase`] is what makes an
    /// operation arriving out of turn an [`ExecutorError::OutOfOrder`] instead
    /// of a silently wrong reply.
    ///
    /// The cost is that acknowledging a call while it is still executing waits
    /// for the execution attempt to finish.
    /// The coordinator never does that, because it acknowledges only after the
    /// conversation has the response.
    state: Mutex<PendingCall>,
}

/// The calls a turn has in flight, under the two names they are looked up by.
///
/// Both maps hold the same slots: the router resolves an interaction by the
/// correlation key it carries, and acknowledgement resolves a recorded response
/// by the tool call id the conversation stores.
#[derive(Default)]
struct Registry {
    by_key: HashMap<HostCallKey, Arc<CallSlot>>,
    by_id: HashMap<String, Arc<CallSlot>>,
}

impl Registry {
    fn insert(&mut self, slot: &Arc<CallSlot>) {
        self.by_key.insert(slot.key.clone(), slot.clone());
        self.by_id.insert(slot.request.id.clone(), slot.clone());
    }

    /// Claim a call for acknowledgement, leaving its route in place.
    ///
    /// The service still has barriers to raise before the call finishes, and a
    /// request it cannot route fails closed, so the route outlives the claim.
    fn claim(&mut self, id: &str) -> Option<Arc<CallSlot>> {
        self.by_id.remove(id)
    }

    /// Drop a finished call's route.
    fn forget(&mut self, slot: &CallSlot) {
        self.by_key.remove(&slot.key);
    }
}

/// Creates MCP-backed executors; configuration and execution context are fixed
/// by the MCP Host when starting the endpoint.
pub(crate) struct TerminalExecutorSource {
    peer: Peer<RoleClient>,
    service: Arc<Service>,
    definitions: IndexMap<String, ToolDefinition>,
    calls: Arc<SyncMutex<Registry>>,
}

/// Keeps the listener, MCP connection, and Host routing task alive for a turn.
pub(crate) struct ExecutionOwner {
    endpoint: Option<Endpoint>,
    client: Option<RunningService<RoleClient, ()>>,
    router: JoinHandle<()>,
}

impl ExecutionOwner {
    /// Cancel pending work and wait for listener/connection cleanup.
    pub(crate) async fn shutdown(mut self) -> Result<(), EndpointError> {
        if let Some(endpoint) = self.endpoint.take() {
            endpoint.shutdown().await?;
        }
        if let Some(client) = self.client.take() {
            client.cancel().await?;
        }
        self.router.abort();
        Ok(())
    }
}

impl Drop for ExecutionOwner {
    fn drop(&mut self) {
        self.router.abort();
    }
}

impl TerminalExecutorSource {
    /// Start the common MCP execution path and its private Host connection.
    pub(crate) async fn start(
        builtins: BuiltinExecutors,
        definitions: &[ToolDefinition],
        tools: &ToolsConfig,
        approvals: Arc<ApprovalStore>,
        invocation: InvocationContext,
        upstream: &Client,
        root: Utf8PathBuf,
    ) -> Result<(Self, ExecutionOwner), EndpointError> {
        let configured = definitions
            .iter()
            .filter_map(|definition| {
                let config = tools.get(&definition.name)?;
                let access =
                    compile_tool_policy(config.access(), &root, &approvals).map_err(|error| {
                        AccessPolicyError {
                            tool: definition.name.clone(),
                            source: Arc::new(error),
                        }
                    });
                Some(ConfiguredTool {
                    definition: definition.clone(),
                    config,
                    access,
                    metadata: Map::new(),
                })
            })
            .collect();
        let (service, host) =
            Service::new(configured, upstream.clone(), builtins, root, invocation)?;
        let progress = service.subscribe_progress();
        let endpoint = Endpoint::start(service).await?;
        let client = endpoint.connect().await?;
        let calls = Arc::new(SyncMutex::new(Registry::default()));
        let router = tokio::spawn(route(host, progress, calls.clone()));
        let source = Self {
            peer: client.peer().clone(),
            service: endpoint.service(),
            definitions: definitions
                .iter()
                .map(|definition| (definition.name.clone(), definition.clone()))
                .collect(),
            calls,
        };
        Ok((source, ExecutionOwner {
            endpoint: Some(endpoint),
            client: Some(client),
            router,
        }))
    }
}

/// Deliver the service's interactions and stderr to the calls they belong to.
///
/// Both streams are drained by one task so a display that stops reading cannot
/// delay a required interaction: progress is dropped, interactions are not.
async fn route(
    mut host: mpsc::Receiver<HostRequest>,
    mut progress: broadcast::Receiver<Progress>,
    calls: Arc<SyncMutex<Registry>>,
) {
    // The service names a call by an `InvocationId` the Host only learns from
    // that call's first interaction, so this index is built here rather than at
    // registration. Being task-local it needs no lock, and it is bounded by the
    // turn's tool calls: the task is aborted when the turn's owner shuts down.
    let mut by_invocation: HashMap<InvocationId, Arc<CallSlot>> = HashMap::new();
    let mut watching_progress = true;
    loop {
        tokio::select! {
            request = host.recv() => {
                let Some(request) = request else { break };
                let Some(slot) = resolve(&calls, &request) else {
                    // The reply sender drops with the request, so the service
                    // sees the Host decline and fails the call closed.
                    warn!(
                        tool = %request.call.request.name,
                        invocation = ?request.call.id,
                        "No Host route for this MCP invocation; failing it closed."
                    );
                    continue;
                };
                by_invocation.insert(request.call.id, slot.clone());
                drop(slot.sender.send(request).await);
            }
            line = progress.recv(), if watching_progress => match line {
                Ok(line) => {
                    let sink = by_invocation
                        .get(&line.id)
                        .and_then(|slot| locked(&slot.stderr).clone());
                    if let Some(sink) = sink {
                        sink(&line.line);
                    }
                }
                // A display that fell behind loses stderr lines. It never
                // delays the interactions in the other branch, which is the
                // point of keeping progress on its own channel.
                Err(ProgressError::Lagged(_)) => {}
                Err(ProgressError::Closed) => watching_progress = false,
            },
        }
    }
}

/// Find the call an interaction belongs to, if it names one.
///
/// The correlation key is what identifies the call: the Host generates it, puts
/// it on the outgoing request, and the service echoes it back untouched.
/// An interaction arriving without a key it issued belongs to somebody else's
/// call, and gets no route.
///
/// The name and arguments are checked afterwards as a consistency assertion,
/// not as a second authority: anything able to supply the key could supply
/// these too.
/// They catch the service echoing the wrong correlation map, which would
/// otherwise show up as a tool that silently never finishes.
fn resolve(calls: &SyncMutex<Registry>, request: &HostRequest) -> Option<Arc<CallSlot>> {
    let key = request
        .call
        .request
        .correlation
        .get(CORRELATION_KEY)
        .and_then(Value::as_str)
        .map(|value| HostCallKey(value.to_owned()))?;
    let slot = locked(calls).by_key.get(&key).cloned()?;
    if slot.request.name != request.call.request.name
        || slot.request.arguments != request.call.request.arguments
    {
        warn!(
            tool_call_id = %slot.request.id,
            expected = %slot.request.name,
            received = %request.call.request.name,
            "Correlation key names a call whose request does not match; refusing the route."
        );
        return None;
    }
    let mut invocation = locked(&slot.invocation);
    match *invocation {
        Some(id) if id != request.call.id => {
            warn!(
                tool_call_id = %slot.request.id,
                bound = ?id,
                received = ?request.call.id,
                "Correlation key is already bound to another invocation; refusing the route."
            );
            return None;
        }
        Some(_) => {}
        None => {
            debug!(
                invocation = ?request.call.id,
                tool_call_id = %slot.request.id,
                tool = %slot.request.name,
                "Associated MCP invocation with Host tool call"
            );
            *invocation = Some(request.call.id);
        }
    }
    drop(invocation);
    Some(slot)
}

impl ExecutorSource for TerminalExecutorSource {
    fn create(
        &self,
        request: ToolCallRequest,
        config: ToolConfigWithDefaults,
    ) -> Option<Box<dyn Executor>> {
        self.definitions.get(&request.name)?;
        let (sender, receiver) = mpsc::channel(8);
        let slot = Arc::new(CallSlot {
            key: HostCallKey::generate(),
            request,
            sender,
            invocation: SyncMutex::new(None),
            stderr: SyncMutex::new(None),
            state: Mutex::new(PendingCall {
                receiver,
                task: None,
                phase: Phase::Idle,
            }),
        });
        locked(&self.calls).insert(&slot);
        Some(Box::new(ToolExecutor {
            arguments: slot.request.arguments.clone(),
            config,
            peer: self.peer.clone(),
            service: self.service.clone(),
            slot,
            formatted: None,
        }))
    }

    fn acknowledge(&self, review: Review) -> BoxFuture<'_, Result<(), ExecutorError>> {
        Box::pin(async move {
            // Claiming makes a second acknowledgement a no-op. Forgetting the
            // call afterwards is what bounds the registry; a turn that ends
            // without acknowledging every call drops the whole source.
            let Some(slot) = locked(&self.calls).claim(&review.response.id) else {
                return Ok(());
            };
            let result = slot.acknowledge(&review).await;
            locked(&self.calls).forget(&slot);
            result
        })
    }
}

/// The Host reply a call is currently parked on.
///
/// Exactly one is outstanding at a time: the service asks for the next thing
/// only once the previous reply reaches it.
enum Phase {
    /// Created, but the MCP call has not been submitted.
    Idle,

    /// Submitted; the Host owes an admission decision.
    Admission(Reply<Admission>),

    /// Admitted; the Host owes execution release.
    Release(Reply<ReleaseDecision>),

    /// A tool asked for input; the Host owes an answer.
    Input {
        id: QuestionId,
        reply: Reply<InputAnswer>,
    },

    /// A result is waiting for the Host to approve or replace its content.
    ///
    /// `offered` is what the service produced.
    /// A Host that does not edit gets this value back, so resources,
    /// annotations, structured content, and error details survive a review that
    /// changed nothing.
    Review {
        offered: ToolResult,
        reply: Reply<ToolResult>,
    },

    /// Content is waiting for the Host to confirm it recorded it.
    Record(Reply<()>),

    /// The MCP call returned; nothing is outstanding.
    Finished,
}

impl Phase {
    /// How this phase reads in a protocol diagnostic.
    fn name(&self) -> &'static str {
        match self {
            Self::Idle => "not yet submitted",
            Self::Admission(_) => "awaiting admission",
            Self::Release(_) => "awaiting release",
            Self::Input { .. } => "awaiting input",
            Self::Review { .. } => "awaiting result review",
            Self::Record(_) => "awaiting recording",
            Self::Finished => "finished",
        }
    }
}

struct PendingCall {
    receiver: mpsc::Receiver<HostRequest>,
    task: Option<JoinHandle<Result<jp_mcp::CallToolResult, McpCallError>>>,
    phase: Phase,
}

enum Received {
    /// Boxed because a call holds one of these only while dispatching it, and
    /// the largest variant is several times the size of the rest.
    Interaction(Box<Interaction>),

    /// The MCP call returned its final result.
    Finished(ToolResult),
}

impl PendingCall {
    /// Wait for the next Host interaction, or for the MCP call to return.
    async fn next(&mut self) -> Result<Received, ExecutorError> {
        let task = self.task.as_mut().ok_or(ExecutorError::HostDisconnected)?;
        tokio::select! {
            request = self.receiver.recv() => {
                let request = request.ok_or(ExecutorError::HostDisconnected)?;
                Ok(Received::Interaction(Box::new(request.interaction)))
            }
            result = task => {
                self.task = None;
                self.phase = Phase::Finished;
                let result = result?.map_err(|error| ExecutorError::Transport(Box::new(error)))?;
                Ok(Received::Finished(
                    from_mcp(result).map_err(ExecutorError::MalformedResult)?,
                ))
            }
        }
    }
}

/// The result the service should deliver, given what the Host recorded.
///
/// An unedited review returns the result the service offered, so resources,
/// annotations, structured content, and error details survive a review that
/// changed nothing.
/// Anything else is rebuilt from the recorded text, which is all the Host's
/// replacement content amounts to.
fn approved(offered: Option<ToolResult>, review: &Review) -> ToolResult {
    match offered {
        Some(offered) if !review.edited => offered,
        _ => ToolResult::from(review.response.result.clone()),
    }
}

impl CallSlot {
    /// Release whichever barrier the call is parked on with the Host's final
    /// content, then drain the call to its MCP response.
    async fn acknowledge(&self, review: &Review) -> Result<(), ExecutorError> {
        let mut state = self.state.lock().await;
        match mem::replace(&mut state.phase, Phase::Finished) {
            // Nothing is outstanding: the call already delivered its result, or
            // never started because preparation failed.
            Phase::Idle | Phase::Finished => return Ok(()),
            Phase::Admission(reply) => drop(reply.send(Ok(Admission::Complete {
                result: approved(None, review),
            }))),
            Phase::Release(reply) => drop(reply.send(Ok(ReleaseDecision::Complete {
                result: approved(None, review),
            }))),
            Phase::Input { reply, .. } => drop(reply.send(Ok(InputAnswer::Complete {
                result: approved(None, review),
            }))),
            Phase::Review { offered, reply } => {
                drop(reply.send(Ok(approved(Some(offered), review))));
            }
            Phase::Record(reply) => drop(reply.send(Ok(()))),
        }
        self.drain(&mut state, review).await
    }

    /// Answer the service's remaining barriers and check what it delivered.
    async fn drain(&self, state: &mut PendingCall, review: &Review) -> Result<(), ExecutorError> {
        loop {
            match state.next().await? {
                Received::Interaction(interaction) => match *interaction {
                    // The Host settled this call at an earlier barrier, so the
                    // content it recorded is also what it approves here.
                    Interaction::Review { result, reply, .. } => {
                        drop(reply.send(Ok(approved(Some(result), review))));
                    }
                    Interaction::Record { reply, .. } => drop(reply.send(Ok(()))),
                    _ => {
                        return Err(ExecutorError::UnexpectedInteraction { phase: "recording" });
                    }
                },
                Received::Finished(delivered) => {
                    let delivered = response(&review.response.id, &delivered);
                    return if delivered.result == review.response.result {
                        Ok(())
                    } else {
                        Err(ExecutorError::DeliveryMismatch)
                    };
                }
            }
        }
    }
}

/// Represents one logical MCP call, including its pending Host interactions.
pub(crate) struct ToolExecutor {
    /// The arguments to execute with, which Host editing may replace.
    arguments: Map<String, Value>,
    config: ToolConfigWithDefaults,
    peer: Peer<RoleClient>,
    service: Arc<Service>,
    slot: Arc<CallSlot>,
    formatted: Option<Formatted>,
}

impl ToolExecutor {
    /// Cancel the service-side invocation, if the service has named it yet.
    fn cancel_invocation(&self) {
        if let Some(id) = *locked(&self.slot.invocation) {
            self.service.cancel_call(id);
        }
    }
}

#[async_trait]
impl Executor for ToolExecutor {
    fn tool_id(&self) -> &str {
        &self.slot.request.id
    }

    fn tool_name(&self) -> &str {
        &self.slot.request.name
    }

    fn arguments(&self) -> &Map<String, Value> {
        &self.arguments
    }

    fn formatted_arguments(&self) -> Option<&Formatted> {
        self.formatted.as_ref()
    }

    fn needs_permission(&self) -> bool {
        !matches!(self.config.run(), RunMode::Unattended | RunMode::Skip)
    }

    fn permission_info(&self) -> Option<PermissionInfo> {
        let run_mode = self.config.run();
        if matches!(run_mode, RunMode::Unattended | RunMode::Skip) {
            return None;
        }
        Some(PermissionInfo {
            tool_id: self.slot.request.id.clone(),
            tool_name: self.slot.request.name.clone(),
            tool_source: self.config.source().clone(),
            run_mode,
            arguments: self.arguments.clone().into(),
        })
    }

    fn set_arguments(&mut self, args: Value) {
        if let Value::Object(arguments) = args {
            self.arguments = arguments;
        }
    }

    async fn prepare(
        &mut self,
        render_arguments: bool,
    ) -> Result<Option<ToolCallResponse>, ExecutorError> {
        let mut state = self.slot.state.lock().await;
        if !matches!(state.phase, Phase::Idle) {
            return Err(ExecutorError::OutOfOrder {
                operation: "be submitted",
                phase: state.phase.name(),
            });
        }
        let mut params = CallToolRequestParams::new(self.slot.request.name.clone());
        params.arguments = Some(self.arguments.clone());
        params.meta = Some(Meta(Map::from_iter([(
            CORRELATION_KEY.into(),
            self.slot.key.0.clone().into(),
        )])));
        let peer = self.peer.clone();
        state.task = Some(tokio::spawn(async move { peer.call_tool(params).await }));
        loop {
            match state.next().await? {
                Received::Interaction(interaction) => match *interaction {
                    Interaction::RenderArguments { reply } => {
                        drop(reply.send(Ok(render_arguments)));
                    }
                    Interaction::Prepare {
                        arguments,
                        formatted_arguments,
                        reply,
                        ..
                    } => {
                        self.arguments = arguments;
                        self.formatted = formatted_arguments;
                        state.phase = Phase::Admission(reply);
                        return Ok(None);
                    }
                    Interaction::Record { recording, reply } => {
                        let response = response(&self.slot.request.id, &recording.result);
                        state.phase = Phase::Record(reply);
                        return Ok(Some(response));
                    }
                    _ => {
                        return Err(ExecutorError::UnexpectedInteraction { phase: "preparing" });
                    }
                },
                Received::Finished(result) => {
                    return Ok(Some(response(&self.slot.request.id, &result)));
                }
            }
        }
    }

    async fn approve(&mut self) -> Result<(), ExecutorError> {
        let mut state = self.slot.state.lock().await;
        let Phase::Admission(reply) = mem::replace(&mut state.phase, Phase::Finished) else {
            state.phase = Phase::Finished;
            return Err(ExecutorError::OutOfOrder {
                operation: "be approved",
                phase: "not awaiting admission",
            });
        };
        reply
            .send(Ok(Admission::Run {
                arguments: self.arguments.clone(),
            }))
            .map_err(|_| ExecutorError::ReplyExpired {
                operation: "approval",
            })?;
        match state.next().await? {
            Received::Interaction(interaction) => match *interaction {
                Interaction::Release {
                    arguments,
                    formatted_arguments,
                    reply,
                } => {
                    self.arguments = arguments;
                    self.formatted = formatted_arguments;
                    state.phase = Phase::Release(reply);
                    Ok(())
                }
                _ => Err(ExecutorError::UnexpectedInteraction { phase: "approving" }),
            },
            // Validating the approved arguments can fail the call outright,
            // which arrives as the MCP response rather than another barrier.
            Received::Finished(result) if result.is_error() => Err(ExecutorError::Rejected {
                message: result.to_text(),
            }),
            Received::Finished(_) => {
                Err(ExecutorError::UnexpectedInteraction { phase: "approving" })
            }
        }
    }

    async fn execute(
        &self,
        answers: &IndexMap<String, Value>,
        cancellation: CancellationToken,
        stderr: Option<StderrSink>,
    ) -> ExecutorResult {
        let mut state = self.slot.state.lock().await;
        *locked(&self.slot.stderr) = stderr;
        let attempt = async {
            match mem::replace(&mut state.phase, Phase::Finished) {
                Phase::Release(reply) => {
                    reply.send(Ok(ReleaseDecision::Execute)).map_err(|_| {
                        ExecutorError::ReplyExpired {
                            operation: "release",
                        }
                    })?;
                }
                Phase::Input { id, reply } => {
                    let answer = answers
                        .get(id.as_str())
                        .ok_or(ExecutorError::MissingAnswer)?
                        .clone();
                    reply.send(Ok(InputAnswer::Answer(answer))).map_err(|_| {
                        ExecutorError::ReplyExpired {
                            operation: "inquiry",
                        }
                    })?;
                }
                phase => {
                    let name = phase.name();
                    state.phase = phase;
                    return Err(ExecutorError::OutOfOrder {
                        operation: "execute",
                        phase: name,
                    });
                }
            }
            let id = &self.slot.request.id;
            match state.next().await? {
                Received::Interaction(interaction) => match *interaction {
                    Interaction::Input {
                        request,
                        supporting,
                        answers,
                        reply,
                    } => {
                        let question = question(request, &supporting);
                        state.phase = Phase::Input {
                            id: question.id.clone(),
                            reply,
                        };
                        Ok(ExecutorResult::NeedsInput {
                            tool_id: id.clone(),
                            tool_name: self.slot.request.name.clone(),
                            source: InquirySource::tool(&self.slot.request.name),
                            question,
                            accumulated_answers: answers,
                        })
                    }
                    Interaction::Review { result, reply, .. } => {
                        let offered = response(id, &result);
                        state.phase = Phase::Review {
                            offered: result,
                            reply,
                        };
                        Ok(ExecutorResult::Completed(offered))
                    }
                    Interaction::Record { recording, reply } => {
                        let response = response(id, &recording.result);
                        state.phase = Phase::Record(reply);
                        Ok(ExecutorResult::Completed(response))
                    }
                    _ => Err(ExecutorError::UnexpectedInteraction { phase: "executing" }),
                },
                Received::Finished(result) => Ok(ExecutorResult::Completed(response(id, &result))),
            }
        };
        let result = tokio::select! {
            biased;
            () = cancellation.cancelled() => Err(ExecutorError::Cancelled),
            result = attempt => result,
        };
        // The service reports an outcome only once the attempt's process has
        // exited and its stderr has been drained, so the sink has nothing left
        // to receive. A question's next attempt brings its own.
        *locked(&self.slot.stderr) = None;
        result.unwrap_or_else(|error| {
            // The call cannot continue, so stop the service-side work rather
            // than leaving it parked on a reply that will never arrive.
            self.cancel_invocation();
            state.phase = Phase::Finished;
            if error.is_call_outcome() {
                return ExecutorResult::Completed(ToolCallResponse {
                    id: self.slot.request.id.clone(),
                    result: Err(error.to_string()),
                });
            }
            ExecutorResult::Failed(error)
        })
    }
}

/// Render a shared input request as the question the terminal prompts with.
///
/// The supporting blocks are the content the tool emitted before its request;
/// the terminal shows them above the prompt.
fn question(request: InputRequest, supporting: &[ContentBlock]) -> Question {
    let preamble = supporting
        .iter()
        .filter_map(ContentBlock::as_text)
        .collect::<Vec<_>>()
        .join("\n\n");
    let mut question = Question::new(request.id, request.label, request.answer_type);
    question.pre_amble = (!preamble.is_empty()).then_some(preamble);
    question.default = request.default;
    question
}

#[cfg(test)]
#[path = "mcp_executor_tests.rs"]
mod tests;
